### ISSUE TITLE
Investigate if the service really handles MQTT payload with odd intervals and partial data

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/WeeWX-MQTTSubscribe#10]

**Comment by R3Spected** [comment]
Hello,
Im sending every 2 Minutes Mqqt messages if the Values is changed and if not i send every 10 minutes on the graphs on weewx i see only points and the current condition monitor reads most of the time N/A some times i see values. any way to fix this?

**Comment by bellrichm** [comment]
@R3Spected, we might need to ask the WeeWX experts, but first a few preliminary questions.
Are you running as a driver or service?
What does the data in the database look like?
What skin are you using to graph?
What is your archive period?

**Comment by bellrichm** [comment]
Ran these two commands in separate terminals.
```
./pubmqtt.py --file test2.data --min-interval 1 --max-interval 10

PYTHONPATH=bin:../weewx/bin python ./bin/user/MQTTSubscribe.py weewx.service.conf --host localhost --type service --binding loop --interval 5 --delay 0 --records 50 --topics test-topic | tee temp.txt
```
With this data file
[test2.data.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4135949/test2.data.txt)

Looking at the logging, it shows the MQTT data being used to update the packet. It also shows that different number of payloads are handlef.

Next up, make the test data have different/missing fields.

**Comment by bellrichm** [comment]
From my tests, the concern I had does not seem to exist.
