### ISSUE TITLE
Using Master (RC03) WifiLogger2 json Results in ERROR user.MQTTSubscribe: (Driver)

### ISSUE THREAD

**Issue by gary-hammer** [bellrichm/WeeWX-MQTTSubscribe#105]
I attempted installing MQTTSubscribe today using the WiFiLogger2
It is configured to send json to my MQTT server and I see that it does.
After installing and configuring MQTTSubscribe and a reboot, I get a failure.
I'm attaching a snip of the logs, let me know if you need any info. This is my test server and I can do whatever you like.
[wifilogger-error.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/5743584/wifilogger-error.txt)

**Comment by bellrichm** [comment]
Hi,
MQTTSubscribe has two defaults that are tripping you up:
1. It is opt out mode. Meaning an attempt to process every field in your json will be performed.
2. All incoming data will be converted into float data.

From your snippet, I am guessing your configuration looks something like this.
```
[[topics]]
    [[[weather/wflexp.json]]]
        [[[[tempout]]]]
            name = outTemp
        [[[[tempin]]]]
            name = inTemp
        [[[[humin]]]]
            name = inHumidity
        [[[[humout]]]]
            name = outHumidity
```
If so, something like this should work.
```
[[topics]]
    [[[weather/wflexp.json]]]
        ignore = true # opt out of processing fields for this topic
        [[[[tempout]]]]
            ignore = false # opt back in for this field
            name = outTemp
        [[[[tempin]]]]
            ignore = false # opt back in for this field
            name = inTemp
        [[[[humin]]]]
            ignore = false # opt back in for this field
            name = inHumidity
        [[[[humout]]]]
            ignore = false # opt back in for this field
            name = outHumidity
```
If you are still having problems, set debug = 1 and capture the log from startup. This will show how the configuration options are being processed.
rich

**Comment by gary-hammer** [comment]
Thanks Rich, that was exactly correct. My hope is to use this vs as a normal logger as the device has a reputation for locking up every 4-5 days if used that way. Publishing to MQTT then reading should solve that issue.

I'll add the rest of the valid fields as opt-in and let it run overnight.

**Comment by gary-hammer** [comment]
I tried adding the other valid fields and generate the same error.
I have set debug = 1 and am attaching my weewx.conf, the log, and a more easily readable json.
No idea why as the fields I selected are numeric.
[weewx.conf.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/5743839/weewx.conf.txt)
[Raw json Values.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/5743838/Raw.json.Values.txt)

**Comment by bellrichm** [comment]
I think it’s the winddir field.  Not sure what to do, because I don’t want to special case ‘—-‘.  Could you remove the winddir and see what happens?
Also, looks like I need to improve the error message to include the field.
We’ll figure something out.
rich

**Comment by bellrichm** [comment]
Oh, and I’m curious - what’s a WiFiLogger2?

**Comment by bellrichm** [comment]
Hmm, i’m thinking maybe an option of; if the conversation to float fails, set the value to None.

**Comment by bellrichm** [comment]
The other option is to convert to string and use StdCalibrate to deal with it.  Not sure if this would work.
rich

**Comment by gary-hammer** [comment]
It is certainly
        [[[[winddir]]]]
            ignore = false # opt back in for this field
            name = windDir

I have taken everything out, then added all back one by one running weewx to a few loops each time.
Do you think the field isn't numeric in the json? Or, how can I test to determine that?

If this is encoded incorrectly, then it will always fail and be None. That wouldn't be a good thing.

**Comment by gary-hammer** [comment]
https://wifilogger.net/

https://www.scaledinstruments.com/shop/davis-instruments/hardware-data-loggers-software/hardware-software-bundles/wifilogger2/

https://www.wxforum.net/index.php?board=143.0

**Comment by bellrichm** [comment]
In the attached wifi-logger.txt
`Dec 26 18:13:17 tester weewxd[8398]: weewx[8398] ERROR user.MQTTSubscribe: (Driver) MessageCallbackProvider on_message_json failed with: could not convert string to float: '---'`
says the value is '---'. I am theorizing it is putting that in the json when the windspd is 0.0. If you look in the raw.json.values.txt, the winddir atually has a valid value and the windspd is >0.
You could map winddir to a field that WeeWX does not know about (name = foo) and add a `type = string` for that field. Then monitor the `LOOP:` values when running WeeWX directly from the command line.

**Comment by gary-hammer** [comment]
I will give this a try in the afternoon.
But, won't this prevent getting the value always, not just when it is zero?

**Comment by bellrichm** [comment]
Yes, this is just to get more information on what the winddir values are. If my theory is correct I would catch the conversion exception and set the value to None, which I believe is what WeeWX expects when windSpeed is 0.

**Comment by gary-hammer** [comment]
That worked a treat.

`LOOP:   2020-12-27 09:45:03 EST (1609080303) altimeter: None, appTemp: 21.167931262994543, barometer: 30.289, cloudbase: 2184.222187480239, consBatteryVoltage: 4.77, dateTime: 1609080303.5697172, dewpoint: 18.0, ET: 0.0, foo: 169.0, heatindex: 26.0, humidex: 26.3, inDewpoint: 41.433420541912994, inHumidity: 31.0, inTemp: 74.0, maxSolarRad: 221.72066159724176, outHumidity: 72.0, outTemp: 26.3, pressure: None, radiation: 158.0, rain: 0.0, rainRate: 0.0, usUnits: 1, UV: 0.7, windchill: 26.3, windDir: None, windGust: 3.0, windGustDir: 247.0, windSpeed: 0.0`

`LOOP:   2020-12-27 09:45:07 EST (1609080307) altimeter: None, appTemp: 20.71325187428316, barometer: 30.289, cloudbase: 2185.0519557236794, consBatteryVoltage: 4.77, dateTime: 1609080307.2087495, dewpoint: 19.0, ET: 0.0, foo: 169.0, heatindex: 26.0, humidex: 26.4, inDewpoint: 41.433420541912994, inHumidity: 31.0, inTemp: 74.0, maxSolarRad: 221.8325768496001, outHumidity: 72.0, outTemp: 26.4, pressure: None, radiation: 158.0, rain: 0.0, rainRate: 0.0, usUnits: 1, UV: 0.7, windchill: 26.4, windDir: None, windGust: 3.0, windGustDir: 247.0, windSpeed: 1.0`

**Comment by gary-hammer** [comment]
I'll use StdCalibrate, Corrections to handle this. ET is reported in the loop correctly (0.001) but shown in the seasons skin as (0.10)
Could be in the seasons skin, but this is my test server and I just run plain jane WeeWX.

**Comment by bellrichm** [comment]
It looks like by default WeeWX is adding the ET loop values to get the archive. See,
https://github.com/weewx/weewx/wiki/Accumulators
Not sure if you want to override it to avg or last...

**Comment by gary-hammer** [comment]
I'd think last, it is the daily value as it starts each day at zero.

**Comment by gary-hammer** [comment]
Plus it is 100 times the value, so maybe I'll poke into the skin and take a
look.

**Comment by bellrichm** [comment]
Interesting hardware.  
I’ll be interested in hearing what you learn about ET.

**Comment by bellrichm** [comment]
I’ve added `conversion_error_to_none`.  If you add `conversion_error_to_none = true` under `[[[winddir]]]`, it should catch the exception and set the field value to None.

**Comment by gary-hammer** [comment]
Working great. Thanks Rich.
Now off to investigate the ET issue. I hope it is in the skin.

**Comment by bellrichm** [comment]
Thanks for letting me know.  I’m going to close this. If you have other issues, you can either open another one or reopen this one.
rich

**Comment by tomdotorg** [comment]
Quick note on this, even though it's closed. I have running a WFL2 as well, and it can be configured to use wflwflexpj.json as the topic instead of wflwflexp.json. The j version uses nulls for all empty fields (no more "---") and omits the quotes from numeric values. I do not know when this feature was introduced in the WFL.

That said, I love the` conversion_error_to_none = true` feature and it will come in handy some day for sure, but probably not needed as this issue's discussion says.

**Comment by bellrichm** [comment]
@tomdotorg Could you provide a link to the documentation? Thanks

**Comment by tomdotorg** [comment]
I don't know of any documentation. I just diffed the files. Let me know if there is something else I can do to help.

[wflwflexp.json.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/8388847/wflwflexp.json.txt)
[wflwflexpj.json.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/8388848/wflwflexpj.json.txt)

**Comment by bellrichm** [comment]
Examples, even better. Thanks

**Comment by gary-hammer** [comment]
> Quick note on this, even though it's closed. I have running a WFL2 as well, and it can be configured to use wflwflexpj.json as the topic instead of wflwflexp.json. The j version uses nulls for all empty fields (no more "---") and omits the quotes from numeric values. I do not know when this feature was introduced in the WFL.
> 
> That said, I love the` conversion_error_to_none = true` feature and it will come in handy some day for sure, but probably not needed as this issue's discussion says.

I'd be interested in where/how you configure the different json types. Also, care to show your setup page from the WFL2? After the updates of the WFL2, mine no longer sends data via MQTT. Connects to the server, no data flows.

**Comment by gary-hammer** [comment]
Hmmm, exactly as I'm set.
Sometimes, the simpler the more inscrutable.
If it is rolling for you, it should for me as well.
I'm on 2.41 for the firmware.
What does your system setup page look like as far as General settings?

**Comment by tomdotorg** [comment]
@gary-hammer here is my main config, assuming that's what you are looking for.. Let me know specifically if not.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/52498/161848862-0c62135f-c1b2-4aeb-9785-c20e9a8a1210.png">

**Comment by gary-hammer** [comment]
> @gary-hammer here is my main config, assuming that's what you are looking for.. Let me know specifically if not.
> 
That is exactly what I was looking for. I, foolishly enough, did not have Upload Data enabled.
Though the WFL2 would faithfully establish a connection, no data would flow.
Now to find how to enable the alternate json.
