### ISSUE TITLE
[Feature Request] Supporte multiple callback types

### ISSUE THREAD

**Issue by jmceara** [bellrichm/WeeWX-MQTTSubscribe#113]
Hi!
Would be very usefull if we can set callback type by topic.
Ex: topic "weather/temperature_1" use 'individual' callback, while topic "weather/b" use 'json' callback type.

**Comment by bellrichm** [comment]
Thanks for opening.  I think with some of the recent refactoring this shouldn’t be too hard.

**Comment by roe-dl** [comment]
I would support that suggestion. I want to add a new data source within the next few weeks, and I also thought about that topic, because one data source is a json data set, but the new one is a single value.

**Comment by bellrichm** [comment]
Current thought is to add a value for the `type` option under `[[message_callback]]` section. I am thinking `mixed`, but I am open to suggestions. A new option, `message_type`, would be added under each `[[[topic-name]]]`. Valid values are `individual`, `json`, or `keyword`.

It would look domething like tjis.
```
[[message_callback]]
    type = mixed # Valid values are individual, json, keyword, or mixed.

[[topics]]
    [[[topic-name-1]]]
        message_type = json # Valid values are individual, json, or keyword
    [[[topic-name-2]]]
        message_type = individual # Valid values are individual, json, or keyword
```

Actually names are subject to change.

**Comment by bellrichm** [comment]
I decided to take a different approach and eliminate the `[[message_callback]]` section. It’s configuration information is now in a `[[[message]]]` section under the `[[topics]]` section. It looks like this.
```
    [[topics]]
        [[[message]]]
            # The format of the MQTT payload.
            # Currently support: individual, json, keyword.
            # Must be specified.
            type = REPLACE_ME
            # When the json is nested, the delimiter between the hierarchies.
            # Default is _.
            flatten_delimiter = _
            # The delimiter between fieldname and value pairs. (field1=value1, field2=value2).
            # Default is is ",".
            keyword_delimiter = ","
            # The separator between fieldname and value pairs. (field1=value1, field2=value2).
            # Default is "=".
            keyword_separator = "="

        [[[topic-1]]]

        [[[topic-2]]]

        [[[topic-3]]]
```

If one has different ‘types’ for different topics, the following can be done.
```
    [[topics]]
        [[[message]]]
            type = individual

        [[[topic-1]]]
            [[[[message]]]]
                type = json

        [[[topic-2]]]

        [[[topic-3]]]
```
This will handle type of `json` for `topic-1` and type of `individual` for `topic-2` and `topic-3`.
A pre-release can be found here, https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v2.0.0-rc07

I may tweak this a bit more, with the hope of eliminating the `message` sections.

**Comment by bellrichm** [comment]
I have decided to leave the `message` section in. This provides some ‘future proofing’ flexibility.

**Comment by bellrichm** [comment]
Has anyone given the release candidate a try?

**Comment by bellrichm** [comment]
@41south Since they are both json you should be fine, UNLESS, they are coming from different brokers/servers. MQTTSubscribe only supports a single broker/server.  
if you run into anything, just shout.

**Comment by bellrichm** [comment]
Beta version here,
https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v2.1.0-rc01

**Comment by bellrichm** [comment]
@jmceara  @roe-dl  any interest in doing some beta testing?

**Comment by roe-dl** [comment]
Actually I am short of time, but I will see if it is better next time.

**Comment by bellrichm** [comment]
@roe-dl Understood. Thanks.

**Comment by Shroomybob** [comment]
Not sure if you need the feedback, but I have this up and working as expected. Most topics using json and one for pressure coming in as keyword. Also thanks for the plugin!

**Comment by bellrichm** [comment]
2.1 has been released

**Comment by andrea-aj** [comment]
Today I managed to get it working. I wanted to inject inTemp and inHumidity from a MySensors device that publishes individual values to the MQTT broker. All my other devices publish in json format, so I used the new "message" section. I had to struggle with name conversion as I was entering "name = inTemp" in the wrong sequence. This is the format that worked for me:
```
    [[topics]]
        [[[message]]]
            type = json
            
        [[[some-topic]]]
            ...
        
        [[[mysensors-out/8/2/1/0/0]]]
            #Convertion to WeeWX name:
            name = inTemp
            [[[[message]]]]
                type = individual

        [[[mysensors-out/8/1/1/0/1]]]
            #Convertion to WeeWX name:
            name = inHumidity
            [[[[message]]]]
                type = individual
```
Rich, thank you for your work, I really appreciate it!
Andrea

**Comment by bellrichm** [comment]
> Today I managed to get it working. I wanted to inject inTemp and inHumidity from a MySensors device that publishes individual values to the MQTT broker. All my other devices publish in json format, so I used the new "message" section. I had to struggle with name conversion as I was entering "name = inTemp" in the wrong sequence. This is the format that worked for me:
> 
> ```
>     [[topics]]
>         [[[message]]]
>             type = json
>             
>         [[[some-topic]]]
>             ...
>         
>         [[[mysensors-out/8/2/1/0/0]]]
>             #Convertion to WeeWX name:
>             name = inTemp
>             [[[[message]]]]
>                 type = individual
> 
>         [[[mysensors-out/8/1/1/0/1]]]
>             #Convertion to WeeWX name:
>             name = inHumidity
>             [[[[message]]]]
>                 type = individual
> ```
> 
> Rich, thank you for your work, I really appreciate it! Andrea

Thanks for you feedback. Greatly appreciated!

My guess, you got tripped up thinking that indention matters. It does not, the brackets ([]) matter. This tripped me up early on too.
