### ISSUE TITLE
[Feature Request] I'd like the option to be able to publish weewx values when running as a service

### ISSUE THREAD

**Issue by crichmon762** [bellrichm/WeeWX-MQTTSubscribe#114]
I know this module is a subscribe thing, and I've got it hooked up to weewx now in subscribe mode for an external sensor.  I'd also like to be able to publish out a value or two from the regular weather station driver.  I noticed when I was debugging it seems that this service re-processes at least the archive records and incorporates the subscribed values into the records.  It's there I'd like to publish out an incoming value from the weather station.  What I don't know is where to add the publish call.  Any hints would be appreciated.
Thx, Chris

**Comment by bellrichm** [comment]
I think this is what you are looking for
https://github.com/matthewwall/weewx-mqtt

**Comment by crichmon762** [comment]
Thanks.  Feel free to close this.
Chris
