### ISSUE TITLE
Archive missing?

### ISSUE THREAD

**Issue by agrieco** [bellrichm/WeeWX-MQTTSubscribe#115]
The install steps show accessing https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/... but its gone?

**Comment by bellrichm** [comment]
Can you post the URL? The two I know of say this
```
wget -P $DOWNLOAD_ROOT https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/v.X.Y.Z.tar.gz
```
This definitely needs improving to explain that X.Y.Z are the versions. Here is the releases page.
https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases
Even though this is a pre-release, it is quit stable.
https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v2.0.0-rc02
And the last release is here.
https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v1.6.2
rich

**Comment by agrieco** [comment]
Thanks for the clarity.  I completely overlooked the releases folder.  I was attempting to browse to https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive to see what versions were available and you get a 404.

This explanation helps get me started.   Perhaps consider linking to releases/latest?

thanks!

**Comment by bellrichm** [comment]
Good idea about the link.  Let’s keep this open as a reminder.

**Comment by bellrichm** [comment]
Wiki updated, readme still needs to be.

**Comment by roe-dl** [comment]
It did not work for me, too.

```
user@LokalWiki:~$ wget https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/v.1.6.2.tar.gz
--2021-01-23 20:38:59--  https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/v.1.6.2.tar.gz
Auflösen des Hostnamens github.com (github.com) … 140.82.121.4
Verbindungsaufbau zu github.com (github.com)|140.82.121.4|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 302 Found
Platz: https://codeload.github.com/bellrichm/WeeWX-MQTTSubscribe/tar.gz/v.1.6.2 [folgend]
--2021-01-23 20:38:59--  https://codeload.github.com/bellrichm/WeeWX-MQTTSubscribe/tar.gz/v.1.6.2
Auflösen des Hostnamens codeload.github.com (codeload.github.com) … 140.82.121.9
Verbindungsaufbau zu codeload.github.com (codeload.github.com)|140.82.121.9|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2021-01-23 20:38:59 FEHLER 404: Not Found.
```

And I replaced X,Y,Z bei the version number.

**Comment by bellrichm** [comment]
@roe-dl 
Sorry, there is a typo that I have not fixed yet.  It should be
```
wget https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/v1.6.2.tar.gz
```
No period after the v.
