### ISSUE TITLE
Wiki does not match msg_id_field configuration options

### ISSUE THREAD

**Issue by hschimke** [bellrichm/WeeWX-MQTTSubscribe#116]
The wiki page: https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Configuring---additional-options

On that page the option to append id values to fields is listed as being 'msg_id'.

In the issue: https://github.com/bellrichm/WeeWX-MQTTSubscribe/issues/80

The issue shows that the correct name is msg_id_field. I tested both with the latest and found that only msg_id_field works.

**Comment by bellrichm** [comment]
Thanks! Fixed in https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Configuring---additional-options/c22ee74ef2c9508942afc5e4e2a591229086a20d
