### ISSUE TITLE
Malformed MQTT Messages Crash WeeWX

### ISSUE THREAD

**Issue by roe-dl** [bellrichm/WeeWX-MQTTSubscribe#117]
The MQTT messages received are out of influence of the user in some way. They can contain wrong characters, malformed JSON data etc. pp. In my case the value was a string instead of a number. WeeWX crashed complaining it could not convert that data to float. As WeeWX usually runs unattended, this behavior is quite dangerous.

So I would suggest to add some checks that the data received by MQTT do not contain characters that can not processed by WeeWX such as letters (['a'..'z'], ['A'..'Z']), control characters (ascii code <32), ascii codes >127. If such character is found MQTTSubscribe could ignore the value (not the whole JSON) and report it to the log.

conversion_type could include some string processing options like converting "OK" to 1 and "Error" or "Failed" to 0.

**Comment by bellrichm** [comment]
Agreed it should not crash. Could you please attach the log.  
Thanks. rich

**Comment by roe-dl** [comment]
First, I attach the json data set that caused the error:

`
{"dateTime": 1611497700.0, "zeitstempel": "2021-01-24T15:15:00+01:00", "stations": {"566055": {"Q": {"state": "OK", "value": 15.3}, "W": {"state": "OK", "value": 102.0, "alarm": 0, "color": "#c5e566"}, "name": "Mahlitzsch", "type": "Pegel"}, "567470": {"Q": {"state": "OK", "value": 21.6}, "W": {"state": "OK", "value": 79.0, "alarm": 0, "color": "#c5e566"}, "name": "Kriebstein UP", "type": "Pegel"}}}
`

**Comment by roe-dl** [comment]
[crash.log](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/5862601/crash.log)

The solution in this case was to set that field to ignore. But then I thought: What is, if there is some problem within the sensor device, and suddenly it sends invalid characters instead of numbers?

**Comment by bellrichm** [comment]
Thanks for the log and data. In the development version, it is logging the error and not crashing. It does skip the whole message. That is by design and will not change. If one wants to attempt to process the message, the  `conversion_error_to_none` might be the solution. (Note, this too is not yet released.)
Here is the pre-release, https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v2.0.0-rc03
The idea of ‘converting’ values is intriguing. I’ll give it some thought.
rich

**Comment by roe-dl** [comment]
As I had no further problems since I am using version 2.0.0-rc03, I guess this issue could be closed. I am not sure if that is my task or that of the owner of the repository, so I will do it now.
