### ISSUE TITLE
Eliminate the wind queue subscription

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/WeeWX-MQTTSubscribe#119]
Currently MQTTSubscribe subscribes to a ‘topic’ used by the wind queue. Although this doesn’t hurt, it is confusing and is a bit of overhead.
See, https://groups.google.com/d/msgid/weewx-user/a2d58678-a9d4-42f9-89b9-248e7a95aee1n%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by roe-dl** [comment]
log and configuration as requested:

[MQTTSubscribe.log](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/5937158/MQTTSubscribe.log)
[weewx.conf.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/5937164/weewx.conf.txt)
