### ISSUE TITLE
TopicManager ignoring record outside of interval

### ISSUE THREAD

**Issue by poblabs** [bellrichm/WeeWX-MQTTSubscribe#122]
Hey there, I'm using your driver in service mode and it appears to be working well. One thing I'm confused on is this error:

`TopicManager ignoring record outside of interval`. What does this mean exactly? 

I have a device which publishes to MQTT every 2.5 seconds, and I'm trying to inject that data to the loop as soon as it arrives. 

Thoughts? Thanks!

**Comment by bellrichm** [comment]
When running as a service MQTTSubscribe attempts to quality control the incoming data so that really old data is not processed.  In hindsight it is too aggressive... The message should have three times, the ‘interval’ start, end, and the incoming time.  You can either ignore the incoming time via ignore_start_time/ignore_end_time or allow data outside the ‘interval’ via adjust_start_time/adjust_end_time.  For more information see, https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Date-Time-processing
-rich

**Comment by poblabs** [comment]
Thanks. I think  ignore_start_time/ignore_end_time is what I want since my MQTT payload does not include a dateTime value.

Another question - you can submit as many loops as you want. Is the service waiting for the driver to submit a loop before it augments this MQTT data? Is there a way to send a separate LOOP from MQTT? 

I'm lucky in that my driver and my MQTT data is ~2.5s so the timing is OK. But thinking if I had a 16 second LOOP, and my MQTT was 2.5s, would the augmented LOOP be 8 values behind? (does that make sense?)

**Comment by bellrichm** [comment]
Yeah, the ignore* sounds like the way to go.  Someday (when I have time...) I should rework some of the datetime stuff.

Yes, the service waits for a loop to ‘arrive’ from the driver.  It treats each loop as a ‘mini archive period’.  So for example, rain would be summed in those theoretical 16 seconds, temperature averaged, etc. All of this behavior controlled by the ‘Accumulator’ configuration in the WeeWX configuration file.

Having the service create its own loop is an interesting idea, but is too far out of the current WeeWX architecture for me...
-rich

**Comment by poblabs** [comment]
No worries - I think for my purposes it'll work just fine. Thanks for the help and insight!

**Comment by poblabs** [comment]
You might be right about the service not being able to submit loop packets because I don't think the service has the `genLoopPackets` function. Anyways probably a non-issue!

**Comment by bellrichm** [comment]
Good point, I’d have to do some real internal WeeWX stuff to make it ‘work’.
From my understanding (and I’m no WeeWX expert), by treating the loop as a ‘mini archive period’ it should accomplish the same, discounting rounding differences, etc.
