### ISSUE TITLE
In indivdual mode, handle same "field names" in different topics

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/WeeWX-MQTTSubscribe#15]
For example, Indoor/temp = inTemp and Outdoor/temp = outTemp
For additional information see, 
https://groups.google.com/d/msg/weewx-user/RpHzL70Svlw/92-1VGvrDAAJ

**Comment by bellrichm** [comment]
Currently the fieldname is the last topic. The plan is to add an option, full_topic_fieldname. When this is False, the current behavior will continue. When it is True, the full topic will be the fieldname. The default will be false.

So, assuming the following data is received from MQTT
msg.topic = weather/outside/temp 
msg.payload = 90

msg.topic = weather/inTemp 
msg.payload = 70

msg.topic = heatIndex 
msg.payload =100

When full_topic_fieldname = False, the packet/record would look like this:
{'temp': 90, 'inTemp': 70, 'heatIndex': 100}

And when full_topic_fieldname = True, the packet/record would look like this:
{'weather/outside/temp': 90, 'weather/inTemp': 70, 'heatIndex': 100}
And, with this mapping
[[label_map]]
	weather/outside/temp = outTemp
	weather/inTemp = inTemp
The packet would be this
{'outTemp': 90, 'inTemp': 70, 'heatIndex': 100}

**Comment by eugen66** [comment]
I added more sensors to the extension and seems to be working great :), but I have not updated with your latest change.
Please let know if you need me to test.

**Comment by bellrichm** [comment]
@eugen66, I realized that you want the ability to subscribe to multiple topics.  Issue #18 has been created for that.  I think a combination of these two should satisfy your needs.
These have been developed and tested in the development branch. I’d greatly appreciate some more real world testing.
Rich
