### ISSUE TITLE
expires_after = None   is ignored

### ISSUE THREAD

**Issue by kevinkey619** [bellrichm/WeeWX-MQTTSubscribe#161]
I've specified  expires_after = None for the pressure value in my weewx.config, but it appears this does absolutely nothing. I'm still getting multiple random blank pressure readings sent to Weather Underground, etc.

**Comment by bellrichm** [comment]
For continuity lets keep the discussion here, https://github.com/bellrichm/WeeWX-MQTTSubscribe/discussions/157. Once we know what is happening we can open specific issues as required.
