### ISSUE TITLE
Unsubscribed Topics

### ISSUE THREAD

**Issue by n7qnm** [bellrichm/WeeWX-MQTTSubscribe#163]
Hi - I've got MQTTSubscribe set up and am seeing some messages that I haven't subscribed to show up.    Here's my config:
 [[topics]]
        # Units for MQTT payloads without unit value.
        # Valid values: US, METRIC, METRICWX
        # Default is: US
        unit_system = US

        [[[skyweather2/state]]]
            [[[[BarometricPressureSeaLevel]]]]
                name = barometer
                ignore = false
                units = kPa
            [[[[SunlightUVIndex]]]]
                name = UV
                ignore = false
            [[[[SunlightVisible]]]]
                name = luminosity
                ignore = false

        [[[skyweather2/WSAQI]]]
            [[[[PM1.0A]]]]
                name = pm1_0
                ignore = false
            [[[[WS_PM2.5A]]]]
                name = pm2_5
                ignore = false
            [[[[WS_PM10A]]]]
                name = pm10_0
                ignore = false

        [[[Radiation]]]
            [[[[uSV]]]]
                name = signal1
                ignore = false

And here's s snip from the log
Jun 17 00:37:46 weewx weewx[6128] DEBUG user.MQTTSubscribe: (Service) data-> final packet is 2022-06-17 00:37:42 PDT (1655451462): 'dateTime': '1655451462', 'outHumidity': '100.0', 'outTemp': '157.6', 'txBatteryStatus': '0', 'usUnits': '1', 'windSpeed': '99.380834998'

I've also got mosquitto_sub running and logging and I DO NOT see this in that log.     Any idea what might be going on?

**Comment by bellrichm** [comment]
Hard to say with that amount of information. More log would be needed.  Ideally from startup to the line you showed.

**Comment by n7qnm** [comment]
OK – I’ll try to find the start – there’s a LOT of debug information; although it looks like the issue I’m chasing (random high wind speeds) is actually coming out of sdr and then I see what looks like an “echo” of the sdr packet.

 

Does MQTTSubscribe decode and report ALL of the packets, or just one’s from subscribed messages?

 

Thx!

**Comment by bellrichm** [comment]
I think you are on the correct path. That line is the final packet, after any MQTT updates. Do it would include the SDR data and any MQTT additional data. A few lines before should show the MQTT data. We could attack it from thst angle.
But I am now pretty sure it is SDR...

**Comment by n7qnm** [comment]
Ah….so that packet is what is used to create the LOOP record?

 

Clay

**Comment by bellrichm** [comment]
I think WeeWX uses the terminology ‘loop packet’ and ‘archive record’.  Packets are accumulated/aggregated into archive records.
If you think it is not MQTTSubscribe, you can disable it by setting `enable = false` in its section. This will certainly reduce the log messages :)

**Comment by bellrichm** [comment]
A bit before 
`Jun 17 00:37:46 weewx weewx[6128] DEBUG user.MQTTSubscribe: (Service) data-> final packet is 2022-06-17 00:37:42 PDT ([1655451462](tel:1655451462)): 'dateTime': '[1655451462](tel:1655451462)', 'outHumidity': '100.0', 'outTemp': '157.6', 'txBatteryStatus': '0', 'usUnits': '1', 'windSpeed': '99.380834998'`, you should see a line starting with `
Packet prior to update is`. This the packet before MQTTSubscribe augments it.  So yes, it ‘touches’ all packets, but if there is no data it essentially flows through untouched.

**Comment by n7qnm** [comment]
Thanks!   Some great insight here – 

 

I’m pretty sure now that it’s SDR; but I have to find what/how.  I went back and just started collecting raw data from RTL and as of now, there’s NOTHING anomalous in there

 

If you want to close this issue, feel free.

 

Clay

**Comment by bellrichm** [comment]
Closing since it appears to not be MQTTSubscribe. If you have any other questions/challenges, feel free to open a new issue or start a discussion topic.
