### ISSUE TITLE
problem while installing...

### ISSUE THREAD

**Issue by PAOK1926** [bellrichm/WeeWX-MQTTSubscribe#173]
i have this problem...

`# /usr/share/weewx/wee_extension --install=/usr/local/bin/WeeWX-MQTTSubscribe/v2.2.2.tar.gz
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 13, in <module>
    import weecfg.extension
  File "/usr/share/weewx/weecfg/__init__.py", line 23, in <module>
    import configobj
ImportError: No module named configobj`

i run python3 and my /etc/default/weewx is
 
WEEWX_PYTHON=python3
WEEWX_PYTHON_ARGS=
WEEWX_BINDIR=/usr/share/weewx
WEEWX_BIN=/usr/bin/weewxd
WEEWX_CFG=/etc/weewx/weewx.conf

**Comment by bellrichm** [comment]
I see you commented in the weewx google group.  This is something with WeeWX, hopefully we will get an answer there.

**Comment by PAOK1926** [comment]
problem solved with this command:
`wee_extension --install=/usr/local/bin/WeeWX-MQTTSubscribe/v2.2.2.tar.gz`
without the full path...

**Comment by bellrichm** [comment]
Thanks. Looks like the wik/readme needs updating.

**Comment by bellrichm** [comment]
Wiki and readme update to remove path.
