### ISSUE TITLE
problem reading values...

### ISSUE THREAD

**Issue by PAOK1926** [bellrichm/WeeWX-MQTTSubscribe#174]
hello again..
now i have this problem...

`Nov 16 00:10:39 AD110-NOC weewx[97244] ERROR user.MQTTSubscribe: (Driver) MessageCallbackProvider on_message_keyword failed to find separator: =

Nov 16 00:10:39 AD110-NOC weewx[97244] ERROR user.MQTTSubscribe: (Driver) **** MessageCallbackProvider Skipping field=15.5 

Nov 16 00:10:39 AD110-NOC weewx[97244] ERROR user.MQTTSubscribe: (Driver) MessageCallbackProvider on_message_keyword failed to find data in: topic=rtl_433/9b13b3f4-rtl433/devices/Bresser-6in1/0/1895852359/temperature_C and payload=b'15.5'
`

**Comment by bellrichm** [comment]
I think you have the wrong payload [type.](https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Configuring#type).
Try this
```
    [[message_callback]]
        type = individual
```

**Comment by PAOK1926** [comment]
thank you very much, it worked...

my problem now is that i have in weewx.conf

`        [[[rtl_433/9b13b3f4-rtl433/devices/Bresser-6in1/0/1895852359/rain_mm]]]
        name = rain
`
mqtt reports rain_mm=0.4 but weewx adds all these values..
now it shows this:

Rain Today | 18.00 cm
Rain Rate | 26.73 cm/h

**Comment by bellrichm** [comment]
From the WeeWX user group the following should work.
```
      [StdWXCalculate]
             [[Delta]]
                [[[rain]]]
                    input = totalRain
```
Where `totalRain` is the name specified in the MQTTSubscribe section

**Comment by bellrichm** [comment]
Any luck getting the correct rain value?
