### ISSUE TITLE
Download "latest" doesn't work

### ISSUE THREAD

**Issue by jens-b** [bellrichm/WeeWX-MQTTSubscribe#211]
Hello i have some problems to install. 
"sudo weectl extension install https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/refs/tags/latest.zip"

give me an html error 404: not found.

how can i install the MQTT Subscribe Extension?

**Comment by bellrichm** [comment]
Sorry about that. The documentation is in flux as I try to get v3 released.
Use this url instead, https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/refs/tags/v2.3.1.zip

**Comment by jens-b** [comment]
Thank you, install works now. But new problem. I tried to create an example config with:
sudo python3 /etc/weewx/bin/user/MQTTSubscribe.py configure --create-example mqttsubscribe.template.conf

i got this error:
Traceback (most recent call last):
  File "/etc/weewx/bin/user/MQTTSubscribe.py", line 392, in <module>
    import weeutil
ModuleNotFoundError: No module named 'weeutil'

where to get the weeutil?

**Comment by bellrichm** [comment]
You’ve installed version 2.3.1, so you need to follow these instructions
https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Installing-and-updating-version-2.x-and-earlier
