### ISSUE TITLE
aggregation for observation?

### ISSUE THREAD

**Issue by poblabs** [bellrichm/WeeWX-MQTTSubscribe#214]
Hey there, I have a 2nd anemometer that I have sending data to mqtt. Using mqttsubscribe as a service i'm able to get `windSpeedFlagpole` and `windGustFlagpole` into the loop just fine. My question is with the archive though. It's averaging both observations which is expected. How can I specify that `windGustFlagpole` should be the max over the archive interval?

**Comment by bellrichm** [comment]
MQTTSubscribe uses core WeeWX functionality to create archive record from the loop packet data. You will want to set the `extractor` of the `windGustFlagpole` to `max`. See, https://github.com/weewx/weewx/wiki/Accumulators, for more information.
Disclaimer: I don’t fully understand WeeWX handling of wind data, but if you just need the max value for a given archive period the above should work.

**Comment by poblabs** [comment]
Awesome! Thanks for pointing me in the right direction
