### ISSUE TITLE
Fineoffset-WH24, WH32B, and WH31E configuation examples

### ISSUE THREAD

**Issue by cweakland** [bellrichm/WeeWX-MQTTSubscribe#220]
[rtl_433-Fineoffset-WH24-WH31E-WH32B.txt](https://github.com/user-attachments/files/17168424/rtl_433-Fineoffset-WH24-WH31E-WH32B.txt)

**Comment by cweakland** [comment]
Thanks for all the work on this project! I wanted to help others out by posting my configuration for several Fineoffset devices. I am a bit of a novice when it comes to GitHub so I am uncertain on how to get things added to the "examples" folder.

**Comment by bellrichm** [comment]
Thank you for your contribution! I will get it added shortly.
