### ISSUE TITLE
global name 'settingd' is not defined

### ISSUE THREAD

**Issue by R3Spected** [bellrichm/WeeWX-MQTTSubscribe#30]
Hello,
When i execute `MQTTSubscribe_install_type=DRIVER wee_extension --install=v1.2.0.tar.gz`
it is fine but after `wee_config --reconfig `
and picking the installed drivers include: 0 for MQTTSubscibeDriver
i get this Traceback:
>     File "/usr/bin/wee_config", line 121, in <module>
>       main()
>     File "/usr/bin/wee_config", line 115, in main
>       config_mgr.run(args, options)
>     File "/usr/share/weewx/weecfg/config.py", line 103, in run
>       self.modify_config(config_dict, options)
>     File "/usr/share/weewx/weecfg/config.py", line 119, in modify_config
>       stn_info = self.get_stn_info(config_dict, options)
>     File "/usr/share/weewx/weecfg/config.py", line 150, in get_stn_info
>       stn_info.update(weecfg.prompt_for_driver_settings(driver, config_dict))
>     File "/usr/share/weewx/weecfg/__init__.py", line 1438, in prompt_for_driver_settings
>       settings[driver_module.DRIVER_NAME] = editor.prompt_for_settings()
>     File "/usr/share/weewx/user/MQTTSubscribe.py", line 823, in prompt_for_settings
>       settingd['topics'] = {}
Im sorry if thats no issue but would be nice if you can help me.

**Comment by bellrichm** [comment]
Looks like I have a typo.  I’ve been a bit busy, so it might take me a bit to get a patch done.
Rich

**Comment by bellrichm** [comment]
I’ve got the typo fixed, but need to look at the install/configure process more.
I’ll report back when I have more information. 
Rich

**Comment by bellrichm** [comment]
Fixed in 1.2.1
