### ISSUE TITLE
Handle cumulative data

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/WeeWX-MQTTSubscribe#40]
Some data may come in as cumulative instead of increments,

**Comment by sussex1** [comment]
Hi
You replied to my cumulative rain topic on weews-user a couple of days ago so I thought i would give MQTTSubscribe a go but am having trouble getting it configured as a driver, any thoughts would be appreciated.   The relevant stuff from weewx.conf is below,   then mosquitto_sub dump    then system.log
Ian
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'
    week_start = 6
    station_type = MQTTSubscribeDriver

##############################################################################

[MQTTSubscribeDriver]
    # This section is for the MQTTSubscribe driver.
    
    # The driver to use:
    driver = user.MQTTSubscribe
    
    # The MQTT server.
    # Default is: localhost
    host = localhost
    
    # The port to connect to.
    # Default is: 1883
    port = 1883
    
    # Maximum period in seconds allowed between communications with the broker.
    # Default is: 60
    keepalive = 60

       #clientid = ESP8266
       username = weewxmqtt
       password = storm5
    
    # Configuration for the message callback.
    [[message_callback]]
        type = individual
    
    # The topics to subscribe to.
    [[topics]]
        unit_system = METRICWX
        [[[weewx/]]]

##############################################################################
...........................................................................................................................................................
sudo mosquitto_sub -d -u weewxmqtt -P storm5 -t weewx/#

Client mosqsub/3886-orangepipc received PUBLISH (d0, q0, r0, m0, 'weewx/bmp_temp', ... (5 bytes))
24.10
Client mosqsub/3886-orangepipc received PUBLISH (d0, q0, r0, m0, 'weewx/baro_mb', ... (7 bytes))
1010.69
Client mosqsub/3886-orangepipc received PUBLISH (d0, q0, r0, m0, 'weewx/outTemp', ... (5 bytes))
20.13
Client mosqsub/3886-orangepipc received PUBLISH (d0, q0, r0, m0, 'weewx/outHumidity', ... (5 bytes))
97.59
Client mosqsub/3886-orangepipc received PUBLISH (d0, q0, r0, m0, 'weewx/windDir', ... (3 bytes))
130
Client mosqsub/3886-orangepipc received PUBLISH (d0, q0, r0, m0, 'weewx/rain', ... (1 bytes))
0
Client mosqsub/3886-orangepipc received PUBLISH (d0, q0, r0, m0, 'weewx/windRaw', ... (2 bytes))
18

...........................................................................................................................................................
System log

Jan 18 10:33:06 orangepipc weewx[2434]: engine: Initializing engine
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading station type MQTTSubscribeDriver (user.MQTTSubscribe)
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Driver wait before retry is 2
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Overlap is 0.0
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager config is {'unit_system': 'METRICWX', 'overlap': 0.0, 'weewx': {}}
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Message callback config is {'type': 'individual'}
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Message callback provider is user.MQTTSubscribe.MessageCallbackProvider
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Client id is MQTTSubscribe-6989
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Clean session is True
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: MQTTSubscribe version is 1.4.1-rc01
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Host is localhost
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Port is 1883
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Keep alive is 60
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Username is weewxmqtt
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Password is set
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Archive topic is None
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Starting loop
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.engine.StdTimeSynch
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.engine.StdTimeSynch
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.engine.StdConvert
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Connected with result code 0
Jan 18 10:33:06 orangepipc weewx[2434]: engine: StdConvert target unit is 0x11
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Connected flags {'session present': 0}
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.engine.StdConvert
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.engine.StdCalibrate
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.engine.StdCalibrate
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.engine.StdQC
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.engine.StdQC
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.wxservices.StdWXCalculate
Jan 18 10:33:06 orangepipc weewx[2434]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=prefer_hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=software, windrun=prefer_hardware, heatindex=prefer_hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=prefer_hardware, inDewpoint=prefer_hardware, ET=prefer_hardware, altimeter=prefer_hardware, cloudbase=prefer_hardware
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Subscribe to weewx has a mid 1 and rc 0
Jan 18 10:33:06 orangepipc weewx[2434]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.wxservices.StdWXCalculate
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.engine.StdArchive
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Archive will use data binding wx_binding
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Record generation will be attempted in 'hardware'
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Using archive interval of 300 seconds (specified by hardware)
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Use LOOP data in hi/low calculations: 1
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Subscribed to topic mid: 1 is size 1 has a QOS of 0
Jan 18 10:33:06 orangepipc weewx[2434]: manager: Daily summary version is 2.0
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Jan 18 10:33:06 orangepipc weewx[2434]: manager: Starting backfill of daily summaries
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.engine.StdArchive
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.restx.StdStationRegistry
Jan 18 10:33:06 orangepipc weewx[2434]: restx: StationRegistry: Registration not requested.
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.restx.StdStationRegistry
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.restx.StdWunderground
Jan 18 10:33:06 orangepipc weewx[2434]: restx: Wunderground: Posting not enabled.
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.restx.StdWunderground
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.restx.StdPWSweather
Jan 18 10:33:06 orangepipc weewx[2434]: restx: PWSweather: Posting not enabled.
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.restx.StdPWSweather
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.restx.StdCWOP
Jan 18 10:33:06 orangepipc weewx[2434]: restx: CWOP: Posting not enabled.
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.restx.StdCWOP
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.restx.StdWOW
Jan 18 10:33:06 orangepipc weewx[2434]: restx: WOW: Posting not enabled.
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.restx.StdWOW
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.restx.StdAWEKAS
Jan 18 10:33:06 orangepipc weewx[2434]: restx: AWEKAS: Posting not enabled.
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.restx.StdAWEKAS
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.engine.StdPrint
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.engine.StdPrint
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Loading service weewx.engine.StdReport
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Finished loading service weewx.engine.StdReport
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Starting up weewx version 3.9.2
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Station does not support reading the time
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Driver no archive topic configured.
Jan 18 10:33:06 orangepipc weewx[2434]: engine: Starting main packet loop.
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:06 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:08 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:08 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:10 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:10 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:12 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:12 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:14 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:14 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:16 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:16 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:18 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:18 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:20 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:20 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:22 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:22 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:24 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:24 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:26 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:26 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:28 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:28 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.
Jan 18 10:33:30 orangepipc weewx[2434]: user.MQTTSubscribe: TopicManager starting queue weewx size is: 0
Jan 18 10:33:30 orangepipc weewx[2434]: user.MQTTSubscribe: Driver queues are empty.

**Comment by bellrichm** [comment]
@sussex1, did you get this working... Did you change the topic to weather/#? Based on what I saw, that was my guess.
Thanks. - rich

**Comment by sussex1** [comment]
Yes its mostly working thanks, still have problem with windDir  going into the loop packets as expected but not making it into the archive record, probably  not a MQTTService issue, I'll keep working on it
Ian

**Comment by bellrichm** [comment]
I got to thinking, and there is some wind specific processing in MQTTSubscribe. So, if set debug to 1 and capture the first couple archive intervals, I’d be happy to take a look
- rich

**Comment by bellrichm** [comment]
Original plan was to add a configuration option that specifies the fields that are cumulative. But after some thought, a new ‘fields’ section that will contain the information necessary to convert the data into WeeWX compatible format. Here is an example of the new section
```
        # Information to map the MQTT data to WeeWX.
        [[[fields]]]
            # The incoming field name from MQTT.
            [[[[temp1]]]
                # The WeeWX name.
                # Default is the name from MQTT.
                name = extraTemp1

                # The conversion type necessary for WeeWX compatibility
                # Valid values: bool, float, int, none
                # Default is float
                conversion_type = float

                # True if the incoming data is cumulative.
                # Valid values: True, False
                # Default is False
                contains_total = False
```

**Comment by sussex1** [comment]
Had a router die so this went on hold for a couple of days but here is the syslog and weewxd output. I think windDir is being published as an integer so maybe that's the problem. Is the new code ready to try?

[syslog_and_weewxd_out.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4094870/syslog_and_weewxd_out.txt)

**Comment by sussex1** [comment]
Router problems susspended play for a while but here are some loop packets and a an archive  from weewxd and syslog 

[syslog_and_weewxd_out.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4095646/syslog_and_weewxd_out.txt)

**Comment by bellrichm** [comment]
Ian,
Thanks for the log. I believe the windDir problem is a bug in MQTTSubscribe. I have opened #44 to track.
Rc01 of 1.5.0 is ready, but doesn’t address #44 
rich

**Comment by sussex1** [comment]
Ok thanks rich
