### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by mattmon** [bellrichm/WeeWX-MQTTSubscribe#49]
What is the difference between a driver and a service? 
why would I choose one over the other?

How can I troubleshoot the installation when no data appears in the database?

**Comment by bellrichm** [comment]
Hi,
The way I think of WeeWX drivers vs services is that the driver is the code that communicates with the weather station and services augment the data processed by the driver.  So if data is only coming via MQTT, you would run as a driver. If you have a weather station already running as a driver, you would run as a service.  Note, I have probably over simplified and the WeeWX docs and forum are the go to place for an expert explanation. Also note, running as a driver is much simpler and when possible the preferred way.

The first step in debugging is to ensure that the MQTT data is ‘arriving’. In the repository there is a utility, mqtt_test.py, that can be used to check that. Some information on using it is here, 
 https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Using-mqtt_test.py-to-check-MQTT

You could also use mosquitto_sub to check. See, https://mosquitto.org/man/mosquitto_sub-1.html 
The advantage of mqtt_test.py is that you pass in the weewx configuration, effectively testing that too.

Once we know the data is ‘arriving’, the next step would be to set debug to 1 in the weewx configuration file and look at the log.  If you attach the log, I’d be happy to take a look.  Please make sure that is from the start of weewx through 2 to 3 archive intervals.

-rich

**Comment by mattmon** [comment]
Thank you. 
I was able to get my installation working with the additional information you posted.
