### ISSUE TITLE
Feature Request: [[deltas]] functionality similar to weewx-sdr 

### ISSUE THREAD

**Issue by mattmon** [bellrichm/WeeWX-MQTTSubscribe#50]
I'm using the MQTTSubscribe driver to ingest topics from my Acurite Atlas.

RTL_433's (feat-atlas branch) mqtt option is being used to capture and send the sensor data.

The atlas only reports rainfall accumulation in inches, so I can't use it directly with WeeWX.

It would be great to have a feature similar to [[deltas]] in WeeWX-SDR that would take the cumulative measures and split into delta measures.

Config  example:
```
  [[deltas]]
        rain = rain_total
```

**Comment by bellrichm** [comment]
Hi,
I think the following is what you are looking for.
```
    # Configuration for the message callback.
    [[message_callback]]

        # Information to map the MQTT data to WeeWX.
        [[[fields]]]
            # The incoming field name from MQTT.
            [[[[raintotal]]]
                # The WeeWX name.
                # Default is the name from MQTT.
                name = rain

                # True if the incoming data is cumulative.
                # Valid values: True, False
                # Default is False
                contains_total = True
```
rich

**Comment by mattmon** [comment]
Thanks for the quick reply :+1: 

Here's what's now in weewx.conf

```
    [[message_callback]]
        type = individual
        [[[fields]]]
            time = timeDate
            wind_dir_deg = windDir
            wind_avg_mi_h = windSpeed
            temperature_F = outTemp
            humidity = outHumidity
            uv = UV
            lux = illuminance
            [[[[rain_in]]]]
                name = rain
                contains_total = True
```
 It's not raining right now, but it looks like it will be soon!

I'll comment in a few hours whether or not I've been successful.

**Comment by bellrichm** [comment]
Is the 
```time = timeDate``` 
etc, actually working? I would thought you would need
```
[[[[time]]]]
  name = timeDate
```
Since I don’t have the real world environment, looking forward to hearing how it goes.
Thanks. - rich

**Comment by mattmon** [comment]
Looks like success, WeeWX has only registered 0.01" of rain so far... but it's not 0!

Yes, time=timeDate seems to be working fine.

You can see the mqtt feed at pioneer.town:1833/wx
(disregard rain24_in - there's bad data in the rain table for the past 24hrs)

**Comment by mattmon** [comment]
I was wrong about timeDate.

My previous config had used [[[label_map]]] so the sensor=name scheme worked fine.

When I switched to [[[fields]]] - having working rain distracted me from having broken everything else, lol!

Here's my fully functional config:
```
        [[[fields]]]
            [[[[time]]]]
                name = timeDate
            [[[[wind_dir_deg]]]]
                name = windDir
            [[[[wind_avg_mi_h]]]]
                name = windSpeed
            [[[[temperature_F]]]]
                name = outTemp
            [[[[humidity]]]]
                name = outHumidity
            [[[[uv]]]]
                name = UV
            [[[[lux]]]]
                name = illuminance
            [[[[rain_in]]]]
                name = rain
                contains_total = True
```

**Comment by bellrichm** [comment]
Good to hear. Yeah, I’ve gone around quite a bit on handling fields. The “fields” approach is a bit verbose, but provides great flexibility. 
If you have any problems, let me know. 
rich
