### ISSUE TITLE
Nested Json

### ISSUE THREAD

**Issue by yesjpm** [bellrichm/WeeWX-MQTTSubscribe#60]
Hi Rich,
I'm using MQTTSubcribe now in a 'keyword' configuration. Works great, thanks!
I would like to use it with nested Json messages (Json -not nested- works fine).
But i'm struggeling with the configuration of the nested fields.

What I would like to do:
Input:
{  ..
  "gas": {
    "totalUse": 2352.545,
    "ts": 1588096800
  },
  ..
}

Requested mapping (from MQTT to loop)
gas_totalUse -> gas
gas_ts -> TsGas

I have this mapping:

        [[[fields]]]
            [[[[gas_totalUse]]]]
            name = gas
            [[[[gas_ts]]]]
            name = TsGas
            conversion_type = int

But I don't get is to work.
[mqtt-log1.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4547995/mqtt-log1.txt)

Regards,
Jaap

**Comment by bellrichm** [comment]
Jaap,
Thanks for the feedback. Much appreciated!
Unfortunately i think you have uncovered a bug. I’m pretty sure i am renaming the field before i have ‘flattened’ it.  I’m a bit backed up with some other updates, but hopefully will get to this soon.
rich

**Comment by bellrichm** [comment]
I've confirmed that in an attempt to optimize the code, things like renaming the field, converting to a different type, dealing with total values was all done before the json was flattened. I am moving all that logic to after flattening. This will result the input field name being the flattened name. 
Net, once I have finished this fix, your field mapping should work as you have it.
rich

**Comment by yesjpm** [comment]
Thanks for solving this so soon!
//Jaap

**Comment by bellrichm** [comment]
Jaap, 
I take it you pulled down master? And therefore no need to create a release...
Thanks. rich
