### ISSUE TITLE
Trying to convert properties I did not specify in the fields parameter

### ISSUE THREAD

**Issue by dshanske** [bellrichm/WeeWX-MQTTSubscribe#63]
I'm using a payload as described in #28.

ERROR user.MQTTSubscribe: MessageCallbackProvider on_message_json failed with: could not convert string to float: 'hPa'
ERROR user.MQTTSubscribe: **** MessageCallbackProvider Ignoring topic=tele/barometer/SENSOR and payload=b'{"Time":1588297297,"BME280":{"Temperature":24.3,"Humidity":38.9,"DewPoint":9.4,"Pressure":1007.1},"PressureUnit":"hPa","TempUnit":"C"}'

I understand it wants to convert fields to floats, but I only care about the fields in the BME280 nested JSON, the temperature units don't need to be converted. Nothing I can see in the documentation says how to tell it to ignore certain properties in the JSON. 

I was previously using this plugin and a custom script that just sent 'barometer' as a topic by itself, but I switched to this embedded Tasmota idea to make things easier and allow me to deploy more sensors in an easier manner.

**Comment by dshanske** [comment]
I tried noting the items in fields setting conversion type to none and it still errors.

**Comment by bellrichm** [comment]
Could you set debug = 1, restart WeeWX, and attach the log.
Thanks. rich

**Comment by dshanske** [comment]
[weewx.log](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4568179/weewx.log)

**Comment by dshanske** [comment]
I'm seeing it note topics being pushed out to MQTT FROM weewx, even though I only told it to listen to one topic.

**Comment by bellrichm** [comment]
Yeah, I see that. The other puzzling thing is a lot of the logging is not showing up.

**Comment by dshanske** [comment]
Any suggestions? I'm going to be going through my weewx.conf section by section anyway...I think it has been a while and I'm sure 4.0 added something I'm missing.

**Comment by bellrichm** [comment]
Sorry, I was confused on my last post. Looking at the log, I don’t see anything that shows conversion type is set to None. What happens if you add something like this.
```
        [[[fields]]]
            [[[[PressureUnit]]]]
                conversion_type = None
```
The MQTTSubscribeService is called for every loop packet. The following just says nothing was changed, because no MQTT data has been received. 
```
DEBUG user.MQTTSubscribe: MQTTSubscribeService data-> final packet is 2020-05-02 12:15:34 EDT (1588436134): dateTime: 1588436134, radiation: 102350, usUnits: 1, UV: 3, windSpeed: 3.0
```
These messages are to be expected.

**Comment by dshanske** [comment]
This is new?

May 02 15:14:35 nuc python3[1372081]: weewx[1372081] DEBUG user.MQTTSubscribe: TopicManager data-> incoming tele/barometer/SENSOR: BME280_DewPoint: 9.6, BME280_Humidity: 40.7, BME280_Temperature: 23.8, pressure: 1011.0, PressureUnit: hPa, TempUnit: C, Time: 1588446875.0
May 02 15:14:35 nuc python3[1372081]: weewx[1372081] ERROR user.MQTTSubscribe: MessageCallbackProvider on_message_json failed with: '>=' not supported between instances of 'int' and 'str'
May 02 15:14:35 nuc python3[1372081]: weewx[1372081] ERROR user.MQTTSubscribe: **** MessageCallbackProvider Ignoring topic=tele/barometer/SENSOR and payload=b'{"Time":1588446875,"BME280":{"Temperature":23.8,"Humidity":40.7,"DewPoint":9.6,"Pressure":1011.0},"PressureUnit":"hPa","TempUnit":"C"}'

**Comment by bellrichm** [comment]
It’s some progress. Could you either attach your current [fields] section and/or the part of the log WeeWX starts.
rich

**Comment by dshanske** [comment]
[[[fields]]]
            # The incoming field name from MQTT.
            #[[[[barometer]]]]
            # The WeeWX name.
            # Default is the name from MQTT.
            #    name = pressure
            
            # The conversion type necessary for WeeWX compatibility
            # Valid values: bool, float, int, none
            # Default is float
            #    conversion_type = float
            
            # True if the incoming data is cumulative.
            # Valid values: True, False
            # Default is False
            #     contains_total = False
            [[[[BME280_Pressure]]]]
                name = pressure
                conversion_type = float
                contains_total = False
            [[[[PressureUnit]]]]
                conversion_type = None
            [[[[TempUnit]]]]
                conversion_type = None

**Comment by bellrichm** [comment]
Well, no surprise there. I guess we will have to up the logging. Can you add the following at the top level of the MQTTSubscribeService section. (Same level that host, etc are) Hopefully this experimental logging will capture something.
```
    logging_level = TRACE
    logging_filename = fully qualified name of a file to log to
```
Then restart WeeWX and attach the log.
Thanks. rich

**Comment by dshanske** [comment]
Nothing new.

INFO MQTTSubscribe port is 1883
INFO MQTTSubscribe keep alive is 60
INFO MQTTSubscribe username is weewx
INFO MQTTSubscribe password is set
INFO Archive topic is None
DEBUG MQTTSubscribe starting loop
DEBUG MQTTSubscribe connected with result code 0
DEBUG MQTTSubscribe connected flags {'session present': 0}
DEBUG MQTTSubscribe subscribe to tele/barometer/SENSOR has a mid 1 and rc 0
DEBUG MQTTSubscribe subscribed to topic mid: 1 is size 1 has a QOS of 0
DEBUG MQTTSubscribeService data-> final packet is 2020-05-02 17:14:17 EDT (1588454057): dateTime: 1588454057, radiation: 5980, usUnits: 1, UV: 0, windSpeed: 2.0
DEBUG MQTTSubscribeService data-> final packet is 2020-05-02 17:14:17 EDT (1588454057): dateTime: 1588454057, radiation: 5980, usUnits: 1, UV: 0, windSpeed: 2.0
DEBUG MQTTSubscribeService data-> final packet is 2020-05-02 17:14:17 EDT (1588454057): dateTime: 1588454057, radiation: 5980, usUnits: 1, UV: 0, windSpeed: 2.0
DEBUG MQTTSubscribeService data-> final packet is 2020-05-02 17:14:27 EDT (1588454067): dateTime: 1588454067, outHumidity: 28.0, outTemp: 71.7, usUnits: 1, windSpeed: 2.0
DEBUG MQTTSubscribeService data-> final packet is 2020-05-02 17:14:27 EDT (1588454067): dateTime: 1588454067, outHumidity: 28.0, outTemp: 71.7, usUnits: 1, windSpeed: 2.0
DEBUG MQTTSubscribeService data-> final packet is 2020-05-02 17:14:27 EDT (1588454067): dateTime: 1588454067, outHumidity: 28.0, outTemp: 71.7, usUnits: 1, windSpeed: 2.0
DEBUG TopicManager data-> incoming tele/barometer/SENSOR: BME280_DewPoint: 9.2, BME280_Humidity: 39.5, BME280_Temperature: 23.8, pressure: 1010.0, PressureUnit: hPa, TempUnit: C, Time: 1588454075
ERROR MessageCallbackProvider on_message_json failed with: '>=' not supported between instances of 'int' and 'str'
ERROR **** MessageCallbackProvider Ignoring topic=tele/barometer/SENSOR and payload=b'{"Time":1588454075,"BME280":{"Temperature":23.8,"Humidity":39.5,"DewPoint":9.2,"Pressure":1010.0},"PressureUnit":"hPa","TempUnit":"C"}'

**Comment by bellrichm** [comment]
Ok, actually that is missing a bunch of the startup log information. I guess i’ll have too dig into the logging code.  It was a work in progress...

**Comment by dshanske** [comment]
The only thing that is compared is the time, if I understand correctly.

**Comment by dshanske** [comment]
Should I test telling it to ignore it?

**Comment by dshanske** [comment]
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] ERROR user.sdr: process did not respond to kill, shutting down anyway
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__: Caught unrecoverable exception:
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****  could not convert string to float: 'hPa'
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****  Traceback (most recent call last):
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 154, in main
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      engine.run()
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 191, in run
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      callback(event)
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/user/MQTTSubscribe.py", line 1063, in new_loop_packet
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      target_data = self.subscriber.get_accumulated_data(topic,
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/user/MQTTSubscribe.py", line 971, in get_accumulated_data
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      return self.manager.get_accumulated_data(topic, start_ts, end_ts, units)
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/user/MQTTSubscribe.py", line 555, in get_accumulated_data
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      accumulator.addRecord(data)
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/accum.py", line 429, in addRecord
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      func(self, record, obs_type, add_hilo, weight)
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/accum.py", line 487, in add_value
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      self[obs_type].addHiLo(val, record['dateTime'])
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/accum.py", line 163, in addHiLo
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      val = to_float(val)
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1250, in to_float
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****      return float(x) if x is not None else None
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****  ValueError: could not convert string to float: 'hPa'
May 02 18:53:52 nuc python3[1407072]: weewx[1407072] CRITICAL __main__:     ****  Exiting.

**Comment by bellrichm** [comment]
Well, that's another step forward. What did you change to get this error?
The lack of logging is making a bit harder. I may have to send you a version that forces the logging.

**Comment by dshanske** [comment]
I eliminated everything in the section but the essential config. I had the defaults from the top of the MQTTSubscribe.py file in there.

**Comment by bellrichm** [comment]
Well that is interesting. Any chance you could attach the broken config file? I’d like to try to reproduce the bug and fix it.
With your last error, I have enough info to fix. It will take me a bit to code it up.
Thanks for your help. rich

**Comment by dshanske** [comment]
I didn't back it up, alas. I copy/pasted the config from the type of the python file and edited it.

**Comment by dshanske** [comment]
A new problem for a new sensor. This is coming from RTL_433

May 06 00:08:14 nuc python3[2113324]: weewx[2113324] ERROR user.sdr: process did not respond to kill, shutting down anyway
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__: Caught unrecoverable exception:
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****  could not convert string to float: 'Fineoffset-WH0290'
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****  Traceback (most recent call last):
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 154, in main
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      engine.run()
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 191, in run
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      callback(event)
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/user/MQTTSubscribe.py", line 1063, in new_loop_packet
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      target_data = self.subscriber.get_accumulated_data(topic,
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/user/MQTTSubscribe.py", line 971, in get_accumulated_data
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      return self.manager.get_accumulated_data(topic, start_ts, end_ts, units)
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/user/MQTTSubscribe.py", line 555, in get_accumulated_data
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      accumulator.addRecord(data)
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/accum.py", line 429, in addRecord
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      func(self, record, obs_type, add_hilo, weight)
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/accum.py", line 487, in add_value
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      self[obs_type].addHiLo(val, record['dateTime'])
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/accum.py", line 163, in addHiLo
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      val = to_float(val)
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1250, in to_float
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****      return float(x) if x is not None else None
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****  ValueError: could not convert string to float: 'Fineoffset-WH0290'
May 06 00:08:14 nuc python3[2113324]: weewx[2113324] CRITICAL __main__:     ****  Exiting.

**Comment by dshanske** [comment]
Tested current master and was able to use it to resolve the issue.

**Comment by bellrichm** [comment]
Thanks for testing and the feedback. I’m gonna’ leave this open until I at least document the option as a comment.

**Comment by bellrichm** [comment]
I created a [prerelease](https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v1.5.3-rc05) that has this update in it. So, I am going to do a bit of housekeeping and close this.
