### ISSUE TITLE
In json payloads handle same named inputs that are in different topic

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/WeeWX-MQTTSubscribe#69]
For example topic1, field temp -> inTemp and topic2, field temp ->outTemp.

Moving the [fields] configuration section under [topics] section seems like a logical choice, but there are a couple challenges. The obvious one is, it would require existing configurations to change or code to be backward compatible. The other is that the purpose of the [message_callback] section is to hold the configuration information for pluggable MQTT message callbacks. This would further couple these with base MQTTSubscribe code. Helper routines might reduce the coupling, but increases the development effort...

The other option is to enable the full_topic_name for json payloads (and maybe eventually keyword). This is a simple implementation, but will result in uglier configuration - having the incoming topic as part of the fieldname. Note, eventually this option could be moved down to the field level. Also, if/when the first option is implemented, leaving this option for backwards compatibility does not bloat the code much.

**Comment by bellrichm** [comment]
@orrious, I ran across this when I tried to enable the bme280 json payload you recently started publishing

**Comment by orrious** [comment]
For me, I make my own sensors and can change the json fields to something unique, however I don't think most others would have the same luxury.  Can you setup field mapping like you've done with individual topics but expand it a level deeper?


        [[[fields]]]
            [[[[sensors/rtl_433]]]]
                [[[[[wind_dir_deg]]]]
                    name = windDir
                [[[[[wind_avg_km_h]]]]]
                    name = windSpeed
                    unit_system = METRIC
                [[[[[temperature_F]]]]]
                    name = outTemp
                    unit_system = US
                [[[[[humidity]]]]]
                    name = outHumidity
                [[[[[battery_ok]]]]]
                    name = rainBatteryStatus
                    conversion_type = bool
                [[[[[rain_in]]]]]
                    name = rain
                    contains_total = True
                    unit_system = US
            [[[[sensors/office/bme280]]]]
                [[[[[pressure_inHg]]]]]
                    name = pressure
                    unit_system = US
                [[[[[temperature_F]]]]]
                    name = inTemp
                    unit_system = US
                [[[[[humidity]]]]]
                    name = inHumidity


[[topics]]
#        unit_system = US    <-  Remove units from here
        use_server_datetime = true
        [[[sensors/rtl_433]]]      #  <- Subscribe to json here
        [[[sensors/office/bme280]]]    #  <- Subscribe to json here

**Comment by bellrichm** [comment]
Yeah, that makes a lot of sense. Probably a bit more than I want to bite off right now. So in the short term I am thinking this.
```
    [[message_callback]]
        type = json
        full_topic_fieldname = True
        [[[fields]]]
            [[[[sensors/rtl_433/time]]]]
                ignore = True
            [[[[sensors/rtl_433/model]]]]
                ignore = True
            [[[[sensors/rtl_433/channel]]]]
                ignore = True
            [[[[sensors/rtl_433/mic]]]]
                ignore = True
            [[[[sensors/rtl_433/wind_dir_deg]]]]
                name = windDir
                conversion_type = int
            [[[[sensors/rtl_433/wind_avg_km_h]]]]
                name = windSpeed
                units = km_per_hour
            [[[[sensors/rtl_433/temperature_F]]]]
                name = outTemp
            [[[[sensors/rtl_433/humidity]]]]
                name = outHumidity
            [[[[sensors/rtl_433/battery_ok]]]]
                name = rainBatteryStatus
                conversion_type = bool
            [[[[sensors/rtl_433/rain_in]]]]
                name = rain
                contains_total = True
            [[[[sensors/office/bme280/time_UTC]]]]
                ignore = True
            [[[[sensors/office/bme280/pressure_inHg]]]]    
                name = pressure            
            [[[[sensors/office/bme280/humidity]]]]    
                name = inHumidity
            [[[[sensors/office/bme280/temperature_F]]]]    
                name = inTemp                                            
        
    [[topics]]
        [[[sensors/rtl_433]]]
        [[[sensors/office/bme280]]]
```
Figuring out the [topic] and ]field] configuration, whether to continue to support pluggable message callbacks, etc will be 2.0 items.

**Comment by orrious** [comment]
What you've proposed works too, especially if it's less work.  Really appreciate all you're putting into this!

**Comment by bellrichm** [comment]
I created a [prerelease](https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v1.5.3-rc05) that has this update in it. So, I am going to do a bit of housekeeping and close this.
