### ISSUE TITLE
Investigate merging topic and field configuration sections

### ISSUE THREAD

**Issue by bellrichm** [bellrichm/WeeWX-MQTTSubscribe#72]
It feels like the fields configuration ‘belongs’ under the topics configuration. There are some challenges to this.
First, the fields configuration is part of the section used by the pluggable message callback providers.
Second, the topics seen by the callback provider is the topic in the message. If wildcards are used in subscribing, these might different than the topics configuration section.

**Comment by bellrichm** [comment]
Upon further review, moving the field configuration under the topic section seems to be straightforward.

**Comment by czechmark** [comment]
FYI your changes for this seem to have broken the renaming "name = XXX" and the units "units = YYY" in the fields configuration

**Comment by bellrichm** [comment]
Thanks! I had noticed the `name` missing but not the `units`. I just committed a fix for the units.  
I still have some more refactoring and tests to write, so there might be additional bugs in the issue72 branch.

**Comment by czechmark** [comment]
That works great... I wasn't expecting that quick a turnaround.

**Comment by bellrichm** [comment]
Thanks for testing!

**Comment by bellrichm** [comment]
I’m thinking of something like this
```
[[Topics]]
	[[[topic name]]]
	msg_id = id
	[[[[temperature_C_73]]]]
		name = extraTemp1
	[[[[temperature_C_42]]]]
		name = extraTemp2
	[[[[temperature_C_207]]]]
		name = extraTemp3
	[[[[time_73]]]]
		name = time_stamp
	[[[[time_42]]]]
		name = time_stamp
	[[[[time_207]]]]
		name = time_stamp
```
So on every incoming message the value in the field named by the msg_id config setting would be appended to every other incoming field name. This name would then be used to lookup the configuration for that field.

Thoughts?

**Comment by bellrichm** [comment]
Completed in 1.6.0
