### ISSUE TITLE
could not convert string to float: '2020-05-17 11:40:05'

### ISSUE THREAD

**Issue by JoePfeiffer** [bellrichm/WeeWX-MQTTSubscribe#75]
Is some configuration necessary to support date/time formats other than Unix epoch?  I'm seeing the following on every packet:
May 17 11:41:10 babs weewx[476826] ERROR user.MQTTSubscribe: MessageCallbackProvider on_message_json failed with: could not convert string to float: '2020-05-17 11:41:09'
May 17 11:41:10 babs weewx[476826] ERROR user.MQTTSubscribe: **** MessageCallbackProvider Ignoring topic=weathersensors and payload=b'{"time":"2020-05-17 11:41:09","model":"Fineoffset-WH65B","id":220,"battery_ok":1,"temperature_C":31.9,"humidity":15,"wind_dir_deg":138,"wind_avg_m_s":0.3825,"wind_max_m_s":1.02,"rain_mm":0,"uv":3158,"uvi":8,"light_lux":104594.0,"mic":"CRC"}'
Running with version 1.5.2 (weewx 4.0.0, python 3.8.3)
If there is a support forum I haven't found, I'll happily redirect my issue/question there.

**Comment by bellrichm** [comment]
Asking for support here is fine.
There are a couple of options. The first is to add `datetime_format` under the `[[topics]]` section. Something like this.
```
[[topics]]
    datetime_format = %Y-%m-%d %H:%M:%S
    [[[subscribed-topic]]]
```
The second is to ignore the datetime in the message and use the datetime of the computer that WeeWX is running on. It would be something like this.
```
     [[message_callback]]
        type = json
        [[[fields]]]
            [[[[time]]]]
                ignore = True
 ```

**Comment by JoePfeiffer** [comment]
Looking at the code a little, it appears the exception is being raised before those options are relevant.  It looks like when self._byteify is called from _on_message_json, it ends up calling self._convert_value.  The default conversion type is 'float', so it tries to do that conversion and fails.  If I add 
        [[[fields]]]
            [[[[time]]]]
            conversion_type = raw
            [[[[model]]]]
            conversion_type = raw
            [[[[mic]]]]
            conversion_type = raw
to weewx.conf
(of course, 'raw' isn't one of the conversion types it understands, but because of that it doesn't do any conversion) I stop getting the exceptions, though I'm now silently not getting readings added to the database.

**Comment by bellrichm** [comment]
What version of MQTTSubscribe are you running? If it’s not 1. 5.3-rc05, could you try it? It can be found here
https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v1.5.3-rc05

**Comment by JoePfeiffer** [comment]
Just tried 1.5.3-rc05; I still need to set the conversion types for those fields to 'raw' to get the packets.

Since I'm getting packets, I wonder if there's a configuration issue elsewhere (note -- I've been running fine using the weewx-sdr driver with rtl_433, except for dropped data when my network load is heavy)?  One thing I'm not at all clear on in the MQTTSubscribe configuration is what 'binding' means.  If I use the default
binding = loop
I see a message on startup of the form
May 19 11:08:20 babs weewx[658339] DEBUG user.MQTTSubscribe: MQTTSubscribeDriver no archive topic configured.
If I set
binding = archive
I don't see a message like that, but the reports still don't get updated.  For what it's worth, here's a typical packet as I receive them:
May 19 11:09:07 babs weewx[658339] DEBUG user.MQTTSubscribe: MessageCallbackProvider data-> incoming topic: weathersensors/outdoors, QOS: 0, retain: 0, payload: b'{"time":"2020-05-19 11:09:06","model":"Fineoffset-WH65B","id":220,"battery_ok":1,"temperature_C":31.2,"humidity":17,"wind_dir_deg":307,"wind_avg_m_s":1.72125,"wind_max_m_s":2.55,"rain_mm":0,"uv":3090,"uvi":7,"light_lux":102718.0,"mic":"CRC"}

**Comment by bellrichm** [comment]
Hmm, the `ignore` setting should have worked. So yeah, could you post your configuration file and I’ll take a look.  Make sure to remove any sensitive information. 
If nothing jumps out, setting `debug = 2` and posting the log from start through one archive period is the next step.
Oh, and keep the binding = loop.

**Comment by JoePfeiffer** [comment]
Thanks -- here it comes!  I've renamed it from weewx.conf to weewx.txt to be able to upload.
[weewx.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4658036/weewx.txt)

**Comment by bellrichm** [comment]
Ah, you are the second person to have this confusion recently. Looks like documentation improvements are needed.
Assuming that you want to replace the sdr driver with MQTTSubscribe, you don't need run MQTTSubscribe as a service. So move the `[[[fields]]]` to the driver section.
```
    # The message handler to use
    [[message_callback]]
        # The format of the MQTT payload.
        # Currently support: individual, json, keyword
        # Must be specified.
        type = json
        [[[fields]]]
            [[[[time]]]]
               ignore = true
            [[[[model]]]]
                ignore = true
            [[[[mic]]]]
               ignore = true
```
Then either remove the service configuration or set ` enable = false`.
The other thing to check is the `[[topics]]` section under the driver. You have different topics configured in the service section vs the driver section. You also have different units. From one of you previous comments it looks like the topic is `weathersensors/outdoors` and unit_system is `METRICWX`.
```
May 19 11:09:07 babs weewx[658339] DEBUG user.MQTTSubscribe: MessageCallbackProvider data-> incoming topic: weathersensors/outdoors, QOS: 0, retain: 0, payload: b'{"time":"2020-05-19 11:09:06","model":"Fineoffset-WH65B","id":220,"battery_ok":1,"temperature_C":31.2,"humidity":17,"wind_dir_deg":307,"wind_avg_m_s":1.72125,"wind_max_m_s":2.55,"rain_mm":0,"uv":3090,"uvi":7,"light_lux":102718.0,"mic":"CRC"}
```
We might need to iterate one or more times, but let know how this goes.

**Comment by JoePfeiffer** [comment]
I think it's getting closer, though still not there...  I've disabled the service as you suggested, and modified the driver configuration as follows:
[MQTTSubscribeDriver]
    # This section is for the MQTTSubscribe driver.                                                                                                                                          

    # The driver to use:                                                                                                                                                                     
    driver = user.MQTTSubscribe

    # The MQTT server.                                                                                                                                                                       
    # Default is: localhost                                                                                                                                                                  
    host = mqtt.pfeifferfamily.net

    # The port to connect to.                                                                                                                                                                
    # Default is: 1883                                                                                                                                                                       
    port = 1883

    # Maximum period in seconds allowed between communications with the broker.                                                                                                              
    # Default is: 60                                                                                                                                                                         
    keepalive = 60

    # Configuration for the message callback.                                                                                                                                                
    [[message_callback]]
        type = json
        [[[fields]]]
            [[[[time]]]]
                ignore = true
            [[[[model]]]]
                ignore = true
            [[[[mic]]]]
                ignore = true

    # The topics to subscribe to.                                                                                                                                                            
    [[topics]]
        unit_system = METRICWX
        [[[weathersensors/outdoors]]]

    [[sensor_map]]
        outTemp = temperature_C
        outHumidity = humidity        
       windDir = wind_dir_deg
        windSpeed = wind_avg_m_s
        windGust = wind_max_m_s
        rain_total = rain_mm
        UV = uvi
        light = light_lux
        txBatteryStatus = battery_ok

I'm still not getting more data into the database -- if I'm understanding the configuration file and interpreting the log properly, it seems like the field names should be getting translated before putting the data in the output queue, but that doesn't seem to be happening:

May 20 14:31:12 babs weewx[760604] DEBUG user.MQTTSubscribe: MQTTSubscribeDriver queues are empty.
May 20 14:31:13 babs weewx[760604] DEBUG user.MQTTSubscribe: MessageCallbackProvider data-> incoming topic: weathersensors/outdoors, QOS: 0, retain: 0, payload: b'{"model":"Fineoffset-WH65\
B","id":220,"battery_ok":1,"temperature_C":30.1,"humidity":14,"wind_dir_deg":290,"wind_avg_m_s":1.33875,"wind_max_m_s":2.04,"rain_mm":0,"uv":2952,"uvi":7,"light_lux":97991.0,"mic":"CRC"}'
May 20 14:31:13 babs weewx[760604] DEBUG user.MQTTSubscribe: MessageCallbackProvider on_message_json ignoring field: model
May 20 14:31:13 babs weewx[760604] DEBUG user.MQTTSubscribe: MessageCallbackProvider on_message_json ignoring field: mic
May 20 14:31:13 babs weewx[760604] DEBUG user.MQTTSubscribe: TopicManager data-> incoming weathersensors/outdoors: battery_ok: 1.0, humidity: 14.0, id: 220.0, light_lux: 97991.0, rain_mm: \
0.0, temperature_C: 30.1, uv: 2952.0, uvi: 7.0, wind_avg_m_s: 1.33875, wind_dir_deg: 290.0, wind_max_m_s: 2.04
May 20 14:31:13 babs weewx[760604] DEBUG user.MQTTSubscribe: TopicManager Added to queue weathersensors/outdoors weathersensors/outdoors 2020-05-20 14:31:13 MDT (1590006673): battery_ok: 1\
.0, dateTime: 1590006673.260579, humidity: 14.0, id: 220.0, light_lux: 97991.0, rain_mm: 0.0, temperature_C: 30.1, usUnits: 17, uv: 2952.0, uvi: 7.0, wind_avg_m_s: 1.33875, wind_dir_deg: 2\
90.0, wind_max_m_s: 2.04
May 20 14:31:14 babs weewx[760604] DEBUG user.MQTTSubscribe: TopicManager starting queue weathersensors/outdoors size is: 1
May 20 14:31:14 babs weewx[760604] DEBUG user.MQTTSubscribe: TopicManager data-> outgoing weathersensors/outdoors: battery_ok: 1.0, dateTime: 1590006673.260579, humidity: 14.0, id: 220.0, \
light_lux: 97991.0, rain_mm: 0.0, temperature_C: 30.1, usUnits: 17, uv: 2952.0, uvi: 7.0, wind_avg_m_s: 1.33875, wind_dir_deg: 290.0, wind_max_m_s: 2.04
May 20 14:31:14 babs weewx[760604] DEBUG user.MQTTSubscribe: MQTTSubscribeDriver data-> final loop packet is weathersensors/outdoors 2020-05-20 14:31:13 MDT (1590006673): battery_ok: 1.0, \
dateTime: 1590006673.260579, humidity: 14.0, id: 220.0, light_lux: 97991.0, rain_mm: 0.0, temperature_C: 30.1, usUnits: 17, uv: 2952.0, uvi: 7.0, wind_avg_m_s: 1.33875, wind_dir_deg: 290.0\
, wind_max_m_s: 2.04

**Comment by bellrichm** [comment]
Yup, you got the right understanding. The naming is done via `fields` configuration section. You want something like this
```
# Configuration for the message callback.                                                                                                                                                
[[message_callback]]
    type = json
    [[[fields]]]
        [[[[time]]]]
            ignore = true
        [[[[model]]]]
            ignore = true
        [[[[mic]]]]
            ignore = true
        [[[[temperature_C]]]]
            name = outTemp 
        [[[[humidity]]]]    
            name  = outHumidity 
        [[[[wind_dir_deg]]]]
            name  = windDir
        [[[[wind_avg_m_s]]]]
            name = windSpeed 
        [[[[wind_max_m_s]]]]
            name = windGust 
        [[[[rain_mm]]]]
            name = rain_total 
        [[[[uvi]]]]
            name  = UV 
        [[[[light_lux]]]]
            name = light 
        [[[[battery_ok]]]]
            name = txBatteryStatus
```

**Comment by JoePfeiffer** [comment]
Thank you!  Now up and running.  It would have taken me a long, long time to get that...  I've got some suggestions on updating the Configuring page in your wiki which address the issues I ran into; I'm attaching them to this comment as a patch.
[update-configuring.patch.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4664321/update-configuring.patch.txt)

**Comment by bellrichm** [comment]
Yeah, the documentation is a work in progress. Thanks for the patch!
Are you good with ignoring the incoming date/time. Or do you want yo try to use it?

**Comment by JoePfeiffer** [comment]
I've now got the time in my packets as a unix timestamp, and I think I'm successfully using it with
[[[[time]]]]
                name = dateTime
                conversion_type = int

At any rate, the times in the outgoing queue are now integers rather than floats!  Should this be correct?

**Comment by bellrichm** [comment]
Yup, sounds like you are fully up and running.
In my poking around the WeeWX internals, you could probably use either floats or integers. But, since they end up as integers in the DB, I’d be inclined to have them as integers.
For a definitive answer, asking the experts in the WeeWX group would be the way to go.
I’m going to close this. Feel free to open another with any other problems/questions.
