### ISSUE TITLE
Add a way to customize similar messages to the same topic Enhancement request

### ISSUE THREAD

**Issue by czechmark** [bellrichm/WeeWX-MQTTSubscribe#80]
I have multiple 433 devices (thermometers) from the same vendor all feeding the same topic.  The messages to the topic are all the same, but the contents identify the individual thermometer.  It would be nice if I could rename the temperature and humidity fields based on a field in the message (in my case something called id).  There are multiple ways I can solve my problem,  changing the 433MHz scanner, post processing the data out of the scanner, processing the data in home assistant and retransmitting it on different topic, ... But if it is easy here it would be nice.

**Comment by bellrichm** [comment]
Seems like it should be doable.  Let me give it some thought while I wrap up #72.

**Comment by bellrichm** [comment]
What format is your messages? The reason I ask is that it will be slightly easier to implement for the json format. Therefore I’d probably initially only implement for the message format you are using.

**Comment by czechmark** [comment]
Yes JSON... Examples below... in my case the field "id" is the unique identifier although I could imagine wanting to use the model as well...

{"time" : "2020-06-19 11:28:10", "model" : "Prologue-TH", "subtype" : 9, "id" : 73, "channel" : 1, "battery_ok" : 0, "temperature_C" : 25.300, "button" : 0, "humidity" : 68}
{"time" : "2020-06-19 11:28:17", "model" : "Prologue-TH", "subtype" : 9, "id" : 42, "channel" : 3, "battery_ok" : 0, "temperature_C" : 26.900, "button" : 0, "humidity" : 63}
{"time" : "2020-06-19 11:28:44", "model" : "Prologue-TH", "subtype" : 9, "id" : 207, "channel" : 2, "battery_ok" : 0, "temperature_C" : 29.700, "button" : 0, "humidity" : 57}

**Comment by bellrichm** [comment]
I’m thinking of something like this
```
[[Topics]]
	[[[topic name]]]
	msg_id = id
	[[[[temperature_C_73]]]]
		name = extraTemp1
	[[[[temperature_C_42]]]]
		name = extraTemp2
	[[[[temperature_C_207]]]]
		name = extraTemp3
	[[[[time_73]]]]
		name = time_stamp
	[[[[time_42]]]]
		name = time_stamp
	[[[[time_207]]]]
		name = time_stamp
```
So on every incoming message the value in the field named by the msg_id config setting would be appended to every other incoming field name. This name would then be used to lookup the configuration for that field.

Thoughts?

**Comment by czechmark** [comment]
Looks good to me.   Only thought is could there be a way to wildcard the id?  So for example, suppose i want to ignore all times so 
[[[time_*]]]
     ignore = true

**Comment by bellrichm** [comment]
At the moment I’d prefer to not handle wildcarding, so I am leaning toward something like this
```
[[Topics]]
	[[[topic name]]]
	msg_id = id
	[[[[temperature_C_73]]]]
		name = extraTemp1
	[[[[temperature_C_42]]]]
		name = extraTemp2
	[[[[temperature_C_207]]]]
		name = extraTemp3
	[[[[time]]]]
		ignore_msg_id = true
		ignore = true
	[[[[foo]]]]
		ignore_msg_id = true
		name = bar
```
Note, I believe the following should work. Basically saying to ignore all the fields except for the ones I ‘turn on’
```
[[Topics]]
	[[[topic name]]]
	msg_id = id
	ignore = true
	[[[[temperature_C_73]]]]
		ignore = false
		name = extraTemp1
	[[[[temperature_C_42]]]]
		ignore = false
		name = extraTemp2
	[[[[temperature_C_207]]]]
		ignore = false
		name = extraTemp3
```

**Comment by czechmark** [comment]
No worries.  Looks good.

**Comment by bellrichm** [comment]
I decided on `msg_id_field` and `ignore_msg_id_field`
```
[[Topics]]
	[[[topic name]]]
	msg_id_field = id
	[[[[temperature_C_73]]]]
		name = extraTemp1
	[[[[temperature_C_42]]]]
		name = extraTemp2
	[[[[temperature_C_207]]]]
		name = extraTemp3
	[[[[time]]]]
		ignore_msg_id_field = true
		ignore = true
	[[[[foo]]]]
		ignore_msg_id_field = true
		name = bar
```
I’m still doing some testing and not sure when I will package it up in a release.  If you are interested, I did create a pre-release, https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases/tag/v1.5.4-rc01

**Comment by bellrichm** [comment]
While working on #82, I realized that the configuration for `individual` payloads, while functional, is a bit 'ugly'. It would look like this.
```
    [[topics]]
        unit_system = METRIC
        [[[parent_topic/field1]]]
		[[[[field1]]]]
			name = weewx_name1
        [[[parent_topic/field2]]]
		[[[[field2]]]]
			name = weewx_name2
        [[[parent_topic/field3]]]
		[[[[field3]]]]
			name = weewx_name3
```

Therefore I will add an option that will use the topic as the field name. This will result in the configuation looking like this.
```
    [[topics]]
        unit_system = METRIC
        use_topic_as_fieldname
        [[[parent_topic/field1]]]
		name = weewx_name1
        [[[parent_topic/field2]]]
		name = weewx_name2
        [[[parent_topic/field3]]]
		name = weewx_name3
```
Note, either configuation will be valid.

**Comment by czechmark** [comment]
Haven't had the time to check this out yet.  But I certainly appreciate the speed at which you implement things.

**Comment by bellrichm** [comment]
No worries.  It’s all in the timing. I was lucky to have some extra free time

**Comment by bellrichm** [comment]
Oh, and from end it is functionally complete with the last commit to master. Just need to package it up into a release.

**Comment by bellrichm** [comment]
I wanted to get the new configuration of the `fields` being under `[topics]`. The release also contains this functionality, so I am going to close this.  When you get around to trying it out and  if you run into any problems/confusion, you can either re-open or open a new issue.
