### ISSUE TITLE
I might be missing something very obvious...

### ISSUE THREAD

**Issue by drbytes** [bellrichm/WeeWX-MQTTSubscribe#82]
So today I installed Weewx, I have no prior experience with it. I collect my own values off of a 5-1 weather station and store them in a db -for fun- but also publish them to a MQTT server so my HomeAssistant can pick them up and work with them.

Station here : http://drbyt.es/weewx/

That all works just fine but I wanted to use the MQTT topics for Weewx and someone pointed me to this driver. I installed and configured it :
```

    # Configuration for the message callback.
    [[message_callback]]
        type = individual

    # The topics to subscribe to.
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/baromin]]]
        [[[pws/sensors/temp]]]
        [[[pws/sensors/dewpt]]]
        [[[pws/sensors/humidity]]]
        [[[pws/sensors/windspeedkph]]]
        [[[pws/sensors/windgustkph]]]
        [[[pws/sensors/rainmm]]]
        [[[pws/sensors/dailyrainmm]]]
        [[[pws/sensors/indoortemp]]]
        [[[pws/sensors/indoorhumidity]]]
        [[[pws/sensors/windspeedmps]]]
        [[[pws/sensors/windgustmps]]]
        [[[pws/sensors/winddircardinal]]]
```

![image](https://user-images.githubusercontent.com/507820/85421162-65625b80-b574-11ea-8e2e-58f54bc5bf52.png)

However, and this could be because I'm new to Weewx, how do I tell Weewx what topic is what kind of data?

**Comment by bellrichm** [comment]
The first question I have is what version did you install? The reason I ask is the latest pre-release, 1.5.4-rc01, changed how to configure MQTTSubscribe.
The second question is, are you running as a driver or service? (This is more of a curiosity question)
Just checking,  `type = individual` means each topic has a single value in the message which is the value for the sensor. 
Hmm, you got me thinking that 1.5.4-rc01 might not work for `type = individual`....
Anyway, we should be able to get you up and running, it just might take a bit of back and forth.
rich

**Comment by drbytes** [comment]
Thx for the fast reply, I'm running the v1.5.3 as a driver since i thought that be the preferred way, I'll attach my weewx.conf

I already tried this : 

```

[MQTTSubscribeDriver]
    driver = user.MQTTSubscribe
    host = 10.0.0.100
    port = 1883
    keepalive = 60
    [[message_callback]]
        type = individual
    
    # The topics to subscribe to.
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/baromin]]]
			name:barometer
		[[[pws/sensors/temp]]]
			name = outTemp
        [[[pws/sensors/dewpt]]]
        [[[pws/sensors/humidity]]]
        [[[pws/sensors/windspeedkph]]]
        [[[pws/sensors/windgustkph]]]
        [[[pws/sensors/rainmm]]]
        [[[pws/sensors/dailyrainmm]]]
        [[[pws/sensors/indoortemp]]]
			name = inTemp
        [[[pws/sensors/indoorhumidity]]]
        [[[pws/sensors/windspeedmps]]]
        [[[pws/sensors/windgustmps]]]
        [[[pws/sensors/winddircardinal]]]
			name = windDir
```

by adding a name under the topic, not sure if that works, /var/log/syslog doesn't seem to show any errors.




[weewx.conf.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4820584/weewx.conf.txt)

**Comment by drbytes** [comment]
Thx for the fast reply, I'm using it as a driver and I'm using the version before the RC1, so 1.5.3

I tried this :  
```

    # The topics to subscribe to.
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/baromin]]]
		name = barometer
	[[[pws/sensors/temp]]]
		name = outTemp
        [[[pws/sensors/dewpt]]]
        [[[pws/sensors/humidity]]]
        [[[pws/sensors/windspeedkph]]]
        [[[pws/sensors/windgustkph]]]
        [[[pws/sensors/rainmm]]]
        [[[pws/sensors/dailyrainmm]]]
        [[[pws/sensors/indoortemp]]]
		name = inTemp
        [[[pws/sensors/indoorhumidity]]]
        [[[pws/sensors/windspeedmps]]]
        [[[pws/sensors/windgustmps]]]
        [[[pws/sensors/winddircardinal]]]
		name = windDir


```

By adding a name under the topic. 

I'm adding my weewx config file below


[weewx.conf.txt](https://github.com/bellrichm/WeeWX-MQTTSubscribe/files/4820599/weewx.conf.txt)

**Comment by bellrichm** [comment]
If you were running rc01, that would be close. This should work. Yeah, it is a bit ugly - which is what I need to think about a bit more.
```
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/baromin]]]
		[[[[baromin]]]]
			name = barometer
        [[[pws/sensors/temp]]]
		[[[[temp]]]]
			name = outTemp
        [[[pws/sensors/dewpt]]]
		[[[[dewpt]]]]
        [[[pws/sensors/humidity]]]
		[[[[humidity]]]]
        [[[pws/sensors/windspeedkph]]]
		[[[[windspeedkph]]]]
        [[[pws/sensors/windgustkph]]]
		[[[[windgustkph]]]]
        [[[pws/sensors/rainmm]]]
		[[[[rainmm]]]]
        [[[pws/sensors/dailyrainmm]]]
		[[[[dailyrainmm]]]]
        [[[pws/sensors/indoortemp]]]
		[[[[indoortemp]]]]
			name = inTemp
        [[[pws/sensors/indoorhumidity]]]
		[[[[indoorhumidity]]]]
        [[[pws/sensors/windspeedmps]]]
		[[[[windspeedmps]]]]
        [[[pws/sensors/windgustmps]]]
		[[[[windgustmps]]]]
        [[[pws/sensors/winddircardinal]]]
		[[[[winddircardinal]]]]
```
Or depending what else is published on `pws/sensors` and your thoughts on wild carding, this should work
```
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/#]]]
		[[[[baromin]]]]
			name = barometer
		[[[[temp]]]]
			name = outTemp
		[[[[dewpt]]]]
		[[[[humidity]]]]
		[[[[windspeedkph]]]]
		[[[[windgustkph]]]]
		[[[[rainmm]]]]
		[[[[dailyrainmm]]]]
		[[[[indoortemp]]]]
			name = inTemp
		[[[[indoorhumidity]]]]
		[[[[windspeedmps]]]]
		[[[[windgustmps]]]]
		[[[[winddircardinal]]]]
```
I’ll follow up with a comment for the 1.5.3 syntax.
rich

**Comment by drbytes** [comment]
I added the last option with the wild carding and had a look in the log, it's definatly able to read it because it stumbles over the winddir which is a string value.

Jun 23 18:59:10 Crunch weewx[48294] INFO weewx.manager: Starting backfill of daily summaries
Jun 23 18:59:10 Crunch weewx[48294] INFO weewx.engine: Starting main packet loop.
Jun 23 18:59:16 Crunch weewx[48294] ERROR user.MQTTSubscribe: (Driver) MessageCallbackProvider on_message_individual failed with: could not convert string to float: O
Jun 23 18:59:16 Crunch weewx[48294] ERROR user.MQTTSubscribe: (Driver) **** MessageCallbackProvider Ignoring topic=pws/sensors/winddir and payload=O
Jun 23 18:59:28 Crunch weewx[48294] ERROR user.MQTTSubscribe: (Driver) MessageCallbackProvider on_message_individual failed with: could not convert string to float: O
Jun 23 18:59:28 Crunch weewx[48294] ERROR user.MQTTSubscribe: (Driver) **** MessageCallbackProvider Ignoring topic=pws/sensors/winddir and payload=O
Jun 23 18:59:40 Crunch weewx[48294] ERROR user.MQTTSubscribe: (Driver) MessageCallbackProvider on_message_individual failed with: could not convert string to float: O
Jun 23 18:59:40 Crunch weewx[48294] ERROR user.MQTTSubscribe: (Driver) **** MessageCallbackProvider Ignoring topic=pws/sensors/winddir and payload=O

So it stumbles over that value but recovers, so we can definatly say it's able to reach the server and read the values. I'll see if it starts to populate weewx and report back.

**Comment by bellrichm** [comment]
For 1.5.3 you want this syntax
```
    [[message_callback]]
        type = individual
        [[[fields]]]
            [[[[baromin]]]]
                name = barometer
            [[[[temp]]]]
                name = outTemp
            [[[[indoortemp]]]]
                name = inTemp
            [[[[winddircardinal]]]]
                name = windDir
```
And either each topic
```
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/baromin]]]
        [[[pws/sensors/temp]]]
        [[[pws/sensors/dewpt]]]
        [[[pws/sensors/humidity]]]
        [[[pws/sensors/windspeedkph]]]
        [[[pws/sensors/windgustkph]]]
        [[[pws/sensors/rainmm]]]
        [[[pws/sensors/dailyrainmm]]]
        [[[pws/sensors/indoortemp]]]
        [[[pws/sensors/indoorhumidity]]]
        [[[pws/sensors/windspeedmps]]]
        [[[pws/sensors/windgustmps]]]
        [[[pws/sensors/winddircardinal]]]
```
Or wildcarding        
```
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/#]]]
```

**Comment by bellrichm** [comment]
Ok, did you upgrade to rc01? Did you add a ‘string’ field to WeeWX to hold the value in winddircardinal? The base WeeWX DB schema is mostly floats, so MQTTSubscribe defaults to converting everything to floats. 

To completely ignore winddircardinal (MQTTSubscribe will not process it and it won’t be added to WeeWX), add this
```
[[[[winddircardinal]]]]
	ignore = True
```

To keep it a string, add the following. This shuts off MQTTSubscribe from doing any type conversion.
```
[[[[winddircardinal]]]]
	conversion_type = None
```

rich

**Comment by drbytes** [comment]
I didn't upgrade to rc1, I'm still on stable.
I added the the winddir ignore and it still wants to parse it. 

So I'll upgrade to the RC1. Do I need to uninstall the other version first?

**Comment by bellrichm** [comment]
You should be able to just upgrade.
I think the reason the `ignore` is being ignored is that you are using rc01 syntax with 1.5.3. In 1.5.3 the `field` config is under the `[[message_callback]]` section. In the rc01, it moved under the `[[topics]]` section. So, i’d also guess no data is making into WeeWX because the `name` mapping is also probably not being picked up.

If you up for it, upgrading is probably the way to go.
rich

**Comment by drbytes** [comment]
Ok, let me just redo everything from scratch. I Still dont see how a topic value is mapped to a weewx value like say if i have 
topic pws/sensors/someTemperatureSensor, how do I need to configure it so I can tell weewx that that topic corresponds to the ouside temperature and that, for instance, another topic named  pws/sensors/someCompletlyDifferentTemperatureSensor should be mapped to the indoor temperature

**Comment by bellrichm** [comment]
Sorry for not being clear. In your case, since it is an ‘individual’ payload and on rc01. 
```
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/#]]] # topic being subscribed to
		[[[[baromin]]]] # topic published to is pws/sensors/baromin
			name = barometer # this is the WeeWX name
```
So MQTTSubscribe takes a message with a topic of /pws/sensors/baromin and creates data for WeeWX in a field with a name of barometer and a value of the message payload.
Does that help?

If you want to see the MQTTSubscribe inputs/outputs, set debug = 1 in weewx.conf.

If you want an almost trace level log, set debug = 2.
rich

**Comment by drbytes** [comment]
Thx, no that is clear I just wasn't sure.

Ok, it's all reinstalled, used the RC1 release and configured this in the weewx config


```

##############################################################################

[MQTTSubscribeDriver]
    # This section is for the MQTTSubscribe driver.
    
    # The driver to use:
    driver = user.MQTTSubscribe
    
    # The MQTT server.
    # Default is: localhost
    host = 10.0.0.100
    
    # The port to connect to.
    # Default is: 1883
    port = 1883
    
    # Maximum period in seconds allowed between communications with the broker.
    # Default is: 60
    keepalive = 60
    
    # Configuration for the message callback.
    [[message_callback]]
        type = individual
    
    # The topics to subscribe to.
    [[topics]]
        unit_system = METRIC
        [[[pws/sensors/baromin]]]
		[[[[baromin]]]]
			name = barometer
        [[[pws/sensors/temp]]]
		[[[[temp]]]]
			name = outTemp
        [[[pws/sensors/dewpt]]]
		[[[[dewpt]]]]
			name = dewpoint
        [[[pws/sensors/humidity]]]
		[[[[humidity]]]]
			name = outHumidity    
        [[[pws/sensors/windspeedkph]]]
		[[[[windspeedkph]]]]			
        [[[pws/sensors/windgustkph]]]
		[[[[windgustkph]]]]
        [[[pws/sensors/rainmm]]]
		[[[[rainmm]]]]
			name = rainRate       
        [[[pws/sensors/dailyrainmm]]]
		[[[[dailyrainmm]]]]
			name = rain
        [[[pws/sensors/indoortemp]]]
		[[[[indoortemp]]]]
			name = inTemp
        [[[pws/sensors/indoorhumidity]]]
		[[[[indoorhumidity]]]]
			name = inHumidity
        [[[pws/sensors/windspeedmps]]]
		[[[[windspeedmps]]]]
			name = windSpeed
        [[[pws/sensors/windgustmps]]]
		[[[[windgustmps]]]]
			name = windGust
        [[[pws/sensors/winddircardinal]]]
		[[[[winddircardinal]]]]
			name = windDir


##############################################################################

```
When I put the debug flag up it does show in the syslog that the values are being read OK.
I'll wait and see if weewx is doing something with it.

Thx!

**Comment by bellrichm** [comment]
Good deal. One last thing. The value specified by `name` must be known yo WeeWX. MQTTSubscribe just creates a dictionary of name/value pairs and passes it of to WeeWX for the heavy lifting.
So, unless you added windspeedkph and windgustkph, I don’t think those are being saved to the db.
I’ll close this. Feel free yo reopen.
And thanks for testing rc01.
Rich
