### ISSUE TITLE
How to specify credentials for MQTT

### ISSUE THREAD

**Issue by earlthesquirrel** [bellrichm/WeeWX-MQTTSubscribe#84]
It's not clear from your documentation whether or not you support credentials for MQTT (at least I couldn't find where to specify them... I don't see anything in what gets loaded into the .conf file.

Also, I'm trying to understand the format of the various inputs.... since I'm generating code from various sensors, I need to figure out the expected inputs.   It would be very useful for users of your SW to have a file of example messages that could be starting points.

I've dumped the weewx schema, and I'm "thinking" that the DB column names might be the keys... so would this be valid?

{ "date_time" : 12345, "outTemp" : 32.4 }

Thanks for making this available btw!!!

**Comment by bellrichm** [comment]
I won’t argue that the documentation is sparse at best, it is a work in a progress. 
You can specify a username password like this
```
[MQTTSubscribeService] or [MQTTSubscribeDriver]
    # The MQTT server.
    # Default is: localhost
    host = localhost
    # The port to connect to.
    # Default is: 1883
    port = 1883
    # Maximum period in seconds allowed between communications with the broker.
    # Default is: 60
    keepalive = 60
    # username for broker authentication.
    # Default is: None
    username = None
    # password for broker authentication.
    # Default is: None
    password = None
```
Ultimately, yes the ‘keys’ need to be the WeeWX names which ultimately are the DB columns. But, if you didn’t have control over the incoming fieldnames, there is mapping functionality. (Note, I think it is dateTime, not date_time).

Not great, but if you browse the top of the code you will see all of the different configuration options. (Technically it would be a breaking change, but the old format is still supported. Probably until the next major release)

I’d suggest/appreciate you starting with 1.5.4-rc01. I moved the configuration options around in this version.

Fire away with any other questions, comments, suggestions, etc.
rich

**Comment by earlthesquirrel** [comment]
Yes, mis-type of the datetime.

My messages look like this:

{"dateTime":1593548177,"outTemp":31.16}
{"dateTime":1593548178,"outHumidity":57}
{"dateTime":1593548178,"barometer":97427}
{"dateTime":1593548179,"pm1_0":0.62}
{"dateTime:1593548179,"co":2.73}
{"dateTime":1593548179,"nh3":0.01}
{"dateTime":1593548180,"no2":15.14}
{"dateTime":1593548180,"extraHumid1":66.31}
{"dateTimej":1593548181,"extraTemp1":30.5}

(I do need to convert some units... or add them... not sure how to specify that... any hints?)

Thanks for the authentication vars, that fixed the first part... now to test some data...(and unit example would be helpful)

ALSO : I loaded the latest release... 1.5.3.  How do I "upgrade" to that?  Just download and reinstall?  Or?

**Comment by bellrichm** [comment]
Yup, just download and reinstall.
Units are very dependent on WeeWX... There is the concept of unit_system, which every value should belong to. But, this can be overridden at the field level. Here is a starting point, with some additional options shown.
```

    # The topics to subscribe to.
    [[topics]
       # Units for MQTT payloads without unit value.
        # Valid values: US, METRIC, METRICWX
        # Default is US
        unit_system = US
        [[[first/topic]]]
            
            # Incoming name
            [[[[temp1]]]
                # The WeeWX name.
                # Default is the name from MQTT.
                name = extraTemp1

                # True if the incoming data should not be processed into WeeWX.
                # Valid values: True, False
                # Default is False
                ignore = False

                # True if the incoming data is cumulative.
                # Valid values: True, False
                # Default is False
                contains_total = False

                # The conversion type necessary for WeeWX compatibility
                # Valid values: bool, float, int, none
                # Default is float
                conversion_type = float

                # The units of the incoming data.
                # Useful if this field's units differ from the topic's unit_system's units.
                # Valid values: see, http://www.weewx.com/docs/customizing.htm#units
                # Default is not set
                # units = km_per_hour
        [[[second/topic]]]
```

**Comment by earlthesquirrel** [comment]
That's definitely one way to fix it.  

I was going to convert on the sensor into the proper units.   So far, things are progressing quickly (thanks!!) 
The only thing off right now is that passing in the barometer value (as barometer not pressure ... there seem to be 2 possible fields) doesn't convert as I'd expect.  

The sensor generates pascals.  So, say it generated 97448.
Converting to inHg I get : 28.7763779035

However in syslog I get an error :

WARNING weewx.qc: 2020-06-30 16:56:46 EDT (1593550606) LOOP value 'barometer' 0.849766079786 outside limits (26.0, 32.5)

So, it's getting converted a 2nd time.  If I don't convert to inHg it still converts (and still falls out of range)

Thoughts?  Should I be passing it as pressure not barometer?

**Comment by earlthesquirrel** [comment]
FYI -- Updating to 1.5.4 fixed the units issues.

Now temps are off -- 'cause I hadn't converted them yet :-)

**Comment by earlthesquirrel** [comment]
Sigh, correcting the temp values and now they're still stuck in Metric.
Time to dump the DB and try again..

**Comment by earlthesquirrel** [comment]
Ok, after a DB dump, run some data for a bit... wait at least a few min for archiving to happen, we're all good! 
Thanks so much!  This really was helpful in getting me started!!

**Comment by bellrichm** [comment]
Not sure why updating to 1.5.4 fixed your units... But, good to hear you are up and running.
