### ISSUE TITLE
I can't get the sum of the values obtained with contains_total

### ISSUE THREAD

**Issue by tixel1** [bellrichm/WeeWX-MQTTSubscribe#94]
I get the average of the values obtained but i need the sum. In this example the obtained value is 0.0045 but i want the sum, 0.003 + 0.006 = 0.009. I don't know how I can get it.
This is the output of the log
Oct 17 13:42:10 rpi weewx[522]: (Service) user.MQTTSubscribe: TopicManager data-> outgoing ESP_Energy_Meter_01/kwh: dateTime: 1602934890.36, kwh: None, usUnits: 17
Oct 17 13:42:10 rpi weewx[522]: (Service) user.MQTTSubscribe: TopicManager data-> outgoing ESP_Energy_Meter_01/kwh: dateTime: 1602934907.72, kwh: 0.003, usUnits: 17
Oct 17 13:42:10 rpi weewx[522]: (Service) user.MQTTSubscribe: TopicManager data-> outgoing ESP_Energy_Meter_01/kwh: dateTime: 1602934925.07, kwh: 0.006, usUnits: 17
Oct 17 13:42:10 rpi weewx[522]: (Service) user.MQTTSubscribe: TopicManager data-> outgoing accumulated ESP_Energy_Meter_01/kwh: dateTime: 1602934926.0, kwh: 0.0045, usUnits: 17

**Comment by bellrichm** [comment]
Remove the contains_total and if the [Accumulator] section does not exist, add the following. If it exists, just add the [[kwh]] subsection.  Note that [Accumulator] is a ‘ top level’ section.
```
[Accumulator]
  [[kwh]]
    extractor = sum
```
For additional information see, https://github.com/weewx/weewx/wiki/Accumulators
