### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by cryptax** [bellrichm/WeeWX-MQTTSubscribe#95]
The documentation says to get package `https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/v.X.Y.Z.tar.gz`, where X, Y and Z are probably version numbers to replace. But there is no `./archive` directory altogether. 

From which place can we get the tar.gz package?

I also tried to build the project using `localbuild.sh`, but it fails because `./localtools/init.sh` is missing.

It looks to me like some files haven't been committed and are missing. ?

**Comment by bellrichm** [comment]
The latest release can be found here
https://github.com/bellrichm/WeeWX-MQTTSubscribe/archive/v1.6.2-rc03.tar.gz
and a list of all releases found here
https://github.com/bellrichm/WeeWX-MQTTSubscribe/releases
