### ISSUE TITLE
Using MQTT external temperature to overwrite (faulty) WMR external temperature

### ISSUE THREAD

**Issue by cryptax** [bellrichm/WeeWX-MQTTSubscribe#96]
Hi,

You have probably seen my post on Weewx forum: https://groups.google.com/g/weewx-user/c/XxvODqXLaQg. Can you help debug the issue ?

So, I have a WMR 200 station whose external temperature (outTemp) is now faulty. I have created a external temperature sensor that uses MQTT. It publishes the temperature on "temperature/jardin" (garden).

The MQTT sensor works correctly, and I confirm I see the MQTT message (mosquitto_sub -h host -t '#' -v).

- The MQTT Subscribe extension is installed, and looks like working as I see several of its logs in weewx.log
- I do not see any message showing evidence that MQTT Subscribe is processing outTemp from my external sensor. The only time I see something in the log with both MQTT Subscribe & outTemp is a line which indicates outTempFault: 1. This is normal : the WMR200 outTemp is faulty. The idea is to have MQTTSubscribe read the outTemp from MQTT and overwrite outTemp in weewx. Is that possible with your extension ?

weewx.conf has:

[Engine]
    # This section configures the internal weewx engines.
    # It is for advanced customization.
    
    [[Services]]
        
        # The list of services the main weewx engine should run:
        prep_services = weewx.engine.StdTimeSynch,
        data_services = user.MQTTSubscribe.MQTTSubscribeService,
...

[MQTTSubscribeService]
    # This section is for the MQTTSubscribe service.
    
    # Turn the service on and off.
    # Default is: true
    # Only used by the service.
    enable = true
    
    # The MQTT server.
    # Default is localhost.
    host = 192.168.0.9
    
    # The port to connect to.
    # Default is 1883.
    port = 1883
    
    # Maximum period in seconds allowed between communications with the broker.
    # Default is 60.
    keepalive = 60
    
    # username for broker authentication.
    # Default is None.
    username = None
    
    # password for broker authentication.
    # Default is None.
    password = None
    
    # The binding, loop or archive.
    # Default is: loop
    # Only used by the service.
    binding = loop
    
    # The message handler to use
    [[message_callback]]
        # The format of the MQTT payload.
        # Currently support: individual, json, keyword
        # Must be specified.
        type = individual
    
    # The topics to subscribe to.
    [[topics]]
        # Units for MQTT payloads without unit value.
        # Valid values: US, METRIC, METRICWX
        # Default is: US
        unit_system = METRIC
        
        [[[temperature/jardin]]]
	    name = outTemp
	    ignore = False
	    contains_total = False
	    conversion_type = float
	    units = degree_C

I am using Weewx 4.1.1 and MQTT Subscribe v1.6.2 rc03.
Thanks.

**Comment by bellrichm** [comment]
It looks like your configuration is not quite right. Try adding the `use_topic_as_fieldname = True` option to the `[[topics]]` section.
```
# The topics to subscribe to.
[[topics]]
    # When true, the fieldname is set to the topic and therefore [[[[fieldname]]]] cannot be used.
    # This allows the [[[[fieldname]]]] configuration to be specified directly under the [[[topic]]].
    # Default is False.
    use_topic_as_fieldname = True

    # Units for MQTT payloads without unit value.
    # Valid values: US, METRIC, METRICWX
    # Default is: US
    unit_system = METRIC
    
    [[[temperature/jardin]]]
    name = outTemp
    ignore = False
    contains_total = False
    conversion_type = float
    units = degree_C
```
For additional information see, https://github.com/bellrichm/WeeWX-MQTTSubscribe/wiki/Configuring---additional-options#use_topic_as_fieldname

**Comment by cryptax** [comment]
You are right. I hadn't understood this option (and I'm not quite sure I still get it) but this fixes the problem hurray! I now have my Weewx reading in data from the MQTT sensor, and it works great.

Thanks!!!

**Comment by bellrichm** [comment]
Yeah, I know its a bit convoluted. It started out because I wanted to support ‘pluggable’ payload parsers - which would enable support for any MQTT format. Early design decisions were strict about what classes had access to what information.  So right now the configuration for all parsers is
```
[[[topic to subscribe to]]]
    [[[[fieldname]]]]
```
This makes sense for payloads with multiple fields, like json and keyword. Not so much  for individual. The ```use_topic_as_fieldname``` is just another way of saying it is of type ```individual```.  And therefore ```[[[[fieldname]]]]``` is not needed.
I’ve been changing the way I support pluggable parsers, so eventually this might get cleaned up.  But its not high on the priority list.
Glad to hear you got it working.
rich
