### ISSUE TITLE
Update to wiki documentation

### ISSUE THREAD

**Issue by hollie** [bellrichm/WeeWX-MQTTSubscribe#99]
Hello @bellrichm 

first of all: thank you for making this WeeWX extension available.

I am trying to set it up to add additional weather info to my setup that mainly consists of a Davis Vantage station plus some other sensors I have around that report via MQTT. This means that I am using the extension in `Service` mode.

While testing the configuration I what puzzled why the `mqtt_test.py` code refused to connect to my broker, that is running on another machine. After some debugging I noticed that you explicitly need to pass the command line option `--type=service` because otherwise the config file is not parsed correctly and the hostname section of the config is not used. Then the script defaults to localhost and of course it then does not work as expected when you have an external broker.

I wanted to add this info to the documentation to avoid that other people waste time trying to debug this. 

Would you mind giving me collaborator access to the wiki so I can make the edit? Or if you prefer not to: could you please add a section to the documentation telling:

---

**Note:** when using the plugin as a service, ensure to pass the commandline option `--type=service` when invoking the test script to ensure that the configuration options are parsed correctly from the configuration file.

---

Thanks,
 Lieven.

**Comment by bellrichm** [comment]
Thanks for the feedback. I’ve updated the wiki. I also think that adding a message to `mqtt_test.py` would make sense, so I am leaving this open as reminder/to do.
rich

**Comment by hollie** [comment]
OK Rich, thank you!
